/* ------------------------------------------------------------------
   Who sounds like whom — generated, do not edit by hand.

   Built by `node scripts/neighbours.mjs` from Last.fm's artist.getSimilar,
   filtered to names this lexicon already lists. It exists so the five names
   on a multiple-choice round can all be plausible: drawn at random from the
   whole index, four of the five answered themselves without a note being
   played.

   Not every artist has an entry, and an entry can be short. Both cases fall
   back to the index, which is what the draw did before this file existed.
   ------------------------------------------------------------------ */

export const NEIGHBOURS: Record<string, string[]> = {
  "Louis Armstrong": ["Ella Fitzgerald", "Count Basie", "Duke Ellington", "Billie Holiday", "Nat King Cole", "Benny Goodman", "Coleman Hawkins", "Sidney Bechet", "Fats Waller", "Dizzy Gillespie", "Jelly Roll Morton", "Sarah Vaughan"],
  "Bix Beiderbecke": ["Jelly Roll Morton", "Fats Waller", "Benny Goodman", "Artie Shaw", "Sidney Bechet", "Louis Armstrong", "Count Basie", "Charlie Christian", "Earl Hines", "Duke Ellington", "Lionel Hampton", "Django Reinhardt"],
  "Rex Stewart": ["Cootie Williams", "Stuff Smith", "Buck Clayton", "Barney Bigard", "Edmond Hall", "Pee Wee Russell", "Bobby Hackett", "Charlie Shavers", "Slam Stewart"],
  "Cootie Williams": ["Rex Stewart", "Barney Bigard", "Buck Clayton", "Edmond Hall", "Stuff Smith", "Charlie Shavers", "Pee Wee Russell"],
  "Buck Clayton": ["Barney Bigard", "Pee Wee Russell", "Rex Stewart", "Charlie Shavers", "Edmond Hall", "Bobby Hackett", "Ruby Braff", "Cootie Williams", "Vic Dickenson", "Harry Edison", "Slam Stewart", "Terry Gibbs"],
  "Harry Edison": ["Jimmy Cobb", "Paul Gonsalves", "Ray Drummond", "Buck Clayton", "Pee Wee Russell", "Ruby Braff"],
  "Roy Eldridge": ["Count Basie", "Earl Hines", "Johnny Hodges", "Artie Shaw", "Clark Terry", "Fats Waller", "Lionel Hampton", "Duke Ellington", "Coleman Hawkins", "Illinois Jacquet", "Benny Goodman", "Benny Carter"],
  "Bobby Hackett": ["Pee Wee Russell", "Edmond Hall", "Barney Bigard", "Johnny Dodds", "Buck Clayton", "Jimmie Noone", "Rex Stewart", "Charlie Shavers", "Ruby Braff", "Cootie Williams"],
  "Charlie Shavers": ["Buck Clayton", "Cootie Williams", "Bobby Hackett", "Rex Stewart", "Ruby Braff", "Harry Edison"],
  "Dizzy Gillespie": ["Charlie Parker", "Clifford Brown", "Clark Terry", "Sonny Stitt", "Cannonball Adderley", "Coleman Hawkins", "Bud Powell", "Dexter Gordon", "Freddie Hubbard", "Sonny Rollins", "Thelonious Monk", "Count Basie"],
  "Fats Navarro": ["Nat Adderley", "Clifford Brown", "Roy Hargrove", "Bud Powell", "Dizzy Gillespie", "Sonny Criss", "Kenny Dorham", "Art Farmer", "Lester Young", "Miles Davis", "Thad Jones", "Blue Mitchell"],
  "Miles Davis": ["John Coltrane", "Wayne Shorter", "Charles Mingus", "Herbie Hancock", "Cannonball Adderley", "Thelonious Monk", "Freddie Hubbard", "Sonny Rollins", "Lee Morgan", "Charlie Parker", "Bill Evans", "Ornette Coleman"],
  "Clifford Brown": ["Dexter Gordon", "Freddie Hubbard", "Charlie Parker", "Dizzy Gillespie", "Lee Morgan", "J.J. Johnson", "Blue Mitchell", "Art Pepper", "Kenny Dorham", "Hank Mobley", "Sonny Rollins", "Bud Powell"],
  "Kenny Dorham": ["Lee Morgan", "Hank Mobley", "Freddie Hubbard", "Sonny Clark", "Dexter Gordon", "Jackie McLean", "Blue Mitchell", "Joe Henderson", "Art Farmer", "Sonny Rollins", "Lou Donaldson", "Cannonball Adderley"],
  "Art Farmer": ["Benny Golson", "Kenny Dorham", "Blue Mitchell", "Hank Mobley", "Nat Adderley", "Zoot Sims", "Sonny Clark", "Lee Morgan", "Freddie Hubbard", "Clifford Brown", "Lee Konitz", "Gerry Mulligan"],
  "Chet Baker": ["Bill Evans", "Gerry Mulligan", "Paul Desmond", "Stan Getz", "Cannonball Adderley", "Miles Davis", "Ella Fitzgerald", "Billie Holiday", "Ben Webster", "Wes Montgomery", "Kenny Burrell", "Art Pepper"],
  "Donald Byrd": ["Bobbi Humphrey", "Lou Donaldson", "Stanley Turrentine", "Lee Morgan", "Freddie Hubbard", "Bobby Hutcherson", "Grant Green", "Horace Silver", "Hank Mobley", "Jimmy Smith", "Gene Harris", "Jackie McLean"],
  "Lee Morgan": ["Hank Mobley", "Freddie Hubbard", "Dexter Gordon", "Jackie McLean", "Wayne Shorter", "Horace Silver", "Joe Henderson", "Sonny Clark", "Kenny Dorham", "Cannonball Adderley", "Sonny Rollins", "McCoy Tyner"],
  "Freddie Hubbard": ["Lee Morgan", "Hank Mobley", "Wayne Shorter", "Joe Henderson", "Dexter Gordon", "Jackie McLean", "Kenny Dorham", "Stanley Turrentine", "Horace Silver", "Cannonball Adderley", "McCoy Tyner", "Sonny Rollins"],
  "Blue Mitchell": ["Lee Morgan", "Lou Donaldson", "Kenny Dorham", "Hank Mobley", "Freddie Hubbard", "Horace Silver", "Jackie McLean", "Stanley Turrentine", "Art Farmer", "Nat Adderley", "Clifford Brown", "Dexter Gordon"],
  "Booker Little": ["Freddie Hubbard", "Eric Dolphy", "Blue Mitchell", "Lee Morgan", "Jackie McLean", "Andrew Hill", "Booker Ervin", "Kenny Dorham", "Hank Mobley", "Woody Shaw", "Harold Land", "Don Cherry"],
  "Woody Shaw": ["Joe Henderson", "Freddie Hubbard", "Lee Morgan", "Bobby Hutcherson", "Andrew Hill", "Jackie McLean", "McCoy Tyner", "Booker Ervin", "Larry Young", "Blue Mitchell", "Wayne Shorter", "Elvin Jones"],
  "Thad Jones": ["J.J. Johnson", "Lee Morgan", "Blue Mitchell", "Kenny Dorham", "Hank Mobley", "Clifford Brown", "Sonny Clark", "Freddie Hubbard", "Johnny Griffin", "Nat Adderley", "Jackie McLean", "Curtis Fuller"],
  "Nat Adderley": ["Freddie Hubbard", "Cannonball Adderley", "Blue Mitchell", "Lee Morgan", "Art Farmer", "Kenny Dorham", "Hank Mobley", "Sonny Criss", "Stanley Turrentine", "Horace Silver", "Harold Land", "Clark Terry"],
  "Bill Hardman": ["Wilbur Ware", "Jackie McLean", "Elvin Jones", "Max Roach", "Don Patterson", "Harold Land", "Wayne Shorter", "Clifford Jordan", "Horace Parlan", "Sonny Criss", "Benny Golson", "Roy Haynes"],
  "Clark Terry": ["Dizzy Gillespie", "Nat Adderley", "Illinois Jacquet", "Clifford Brown", "Blue Mitchell", "Sonny Rollins", "Oscar Peterson", "Coleman Hawkins", "Sonny Stitt", "Art Farmer", "Cannonball Adderley", "Lee Morgan"],
  "Maynard Ferguson": ["Buddy Rich", "Count Basie", "Arturo Sandoval", "Roy Hargrove", "Clifford Brown", "Wynton Marsalis", "Dizzy Gillespie", "Freddie Hubbard", "Dave Brubeck", "Clark Terry", "Kenny Dorham", "Sonny Stitt"],
  "Shorty Rogers": ["Jimmy Giuffre", "Lee Konitz", "Jimmy Raney", "Serge Chaloff", "George Shearing", "Shelly Manne", "Gerry Mulligan", "Woody Shaw", "Zoot Sims", "Art Pepper", "Art Farmer", "Thad Jones"],
  "Conte Candoli": ["Leroy Vinnegar", "Terry Gibbs", "Herb Geller", "Cecil Payne", "Wardell Gray", "Ruby Braff", "Kenny Clarke", "Bennie Green", "Al Haig", "Arnett Cobb", "Jon Faddis", "Shelly Manne"],
  "Don Cherry": ["Albert Ayler", "Cecil Taylor", "Pharoah Sanders", "Ornette Coleman", "Archie Shepp", "Andrew Hill", "Eric Dolphy", "Marion Brown", "Dave Holland", "Grachan Moncur III", "Miles Davis", "John Coltrane"],
  "Ruby Braff": ["Wardell Gray", "Buck Clayton", "Terry Gibbs", "Bobby Hackett", "Vic Dickenson", "Al Cohn", "Harry Edison", "Slide Hampton", "Frank Rosolino", "Edmond Hall", "Jon Faddis", "Rex Stewart"],
  "Jon Faddis": ["Randy Brecker", "Ruby Braff", "Harry Edison", "Clark Terry", "Terry Gibbs", "Wynton Marsalis", "Buck Clayton", "Bennie Green"],
  "Randy Brecker": ["Bob Berg", "Bob Mintzer", "Steve Gadd", "Danilo Perez", "Jon Faddis", "Greg Osby", "Stefon Harris"],
  "Arturo Sandoval": ["Chucho Valdes", "Maynard Ferguson", "Wynton Marsalis", "Dizzy Gillespie", "Roy Hargrove", "Eddie Palmieri", "Chick Corea", "Ron Carter", "Gonzalo Rubalcaba", "Dexter Gordon", "Cal Tjader", "Buddy Rich"],
  "Wynton Marsalis": ["Oscar Peterson", "Roy Hargrove", "Miles Davis", "Freddie Hubbard", "Coleman Hawkins", "Clifford Brown", "Art Pepper", "Thelonious Monk", "Cannonball Adderley", "Branford Marsalis", "Ben Webster", "Houston Person"],
  "Terence Blanchard": ["Roy Hargrove", "Wynton Marsalis", "Ambrose Akinmusire", "Tom Harrell", "Dave Douglas", "Joshua Redman", "Jason Moran", "Aaron Parks", "Walter Smith III", "Branford Marsalis", "Bill Frisell", "Michael Brecker"],
  "Roy Hargrove": ["Kenny Garrett", "Joshua Redman", "Freddie Hubbard", "Wynton Marsalis", "Michael Brecker", "Clifford Brown", "Blue Mitchell", "Wayne Shorter", "McCoy Tyner", "Herbie Hancock", "Joe Henderson", "Lee Morgan"],
  "Tom Harrell": ["Dave Douglas", "Mark Turner", "Woody Shaw", "Ambrose Akinmusire", "Cedar Walton", "Wynton Marsalis", "Enrico Rava", "Roy Hargrove", "Blue Mitchell", "Jason Moran", "Freddie Hubbard", "Kenny Barron"],
  "Dave Douglas": ["Ambrose Akinmusire", "Kris Davis", "Jason Moran", "Tom Harrell", "Bill Frisell", "Mark Turner", "Vijay Iyer", "Linda May Han Oh", "Craig Taborn", "Mary Halvorson", "Charles Lloyd", "Dave Holland"],
  "Kenny Wheeler": ["John Abercrombie", "Enrico Rava", "Paul Motian", "Dave Holland", "Bobo Stenson", "Woody Shaw", "Keith Jarrett", "Gary Burton", "Peter Erskine", "Charlie Haden", "Ralph Towner", "Steve Swallow"],
  "Enrico Rava": ["John Abercrombie", "Bobo Stenson", "Kenny Wheeler", "Charles Lloyd", "Ralph Towner", "Gary Peacock", "Tord Gustavsen", "Joe Lovano", "Fred Hersch", "Keith Jarrett", "Peter Erskine", "Dave Holland"],
  "Ingrid Jensen": ["Seamus Blake", "Lage Lund", "Randy Brecker", "Mel Lewis", "Bill Stewart", "Eric Harland", "Stefon Harris", "Vincent Herring"],
  "Ambrose Akinmusire": ["Immanuel Wilkins", "Dave Douglas", "Vijay Iyer", "Gerald Clayton", "Chris Potter", "Jason Moran", "Bill Frisell", "Charles Lloyd", "Aaron Parks", "Kurt Rosenwinkel", "Mark Turner", "Mary Halvorson"],
  "Avishai Cohen": ["Aaron Parks", "Brad Mehldau", "Joshua Redman", "Vijay Iyer", "Michel Petrucciani", "Tord Gustavsen", "Joey Alexander", "Kenny Barron", "Chick Corea", "Christian McBride", "John Scofield", "Charles Lloyd"],
  "Marquis Hill": ["Walter Smith III", "Ambrose Akinmusire", "Keyon Harrold", "Immanuel Wilkins", "Makaya McCraven", "Robert Glasper", "Chris Potter", "Roy Hargrove", "Woody Shaw", "Gerald Clayton", "Ben Williams", "Mark Turner"],
  "Keyon Harrold": ["Marquis Hill", "Robert Glasper", "Ambrose Akinmusire", "Christian McBride", "Gerald Clayton", "Roy Hargrove", "Immanuel Wilkins", "Makaya McCraven", "Nubya Garcia", "Julian Lage", "Dave Douglas", "Lakecia Benjamin"],
  "Coleman Hawkins": ["Ben Webster", "Lester Young", "Dexter Gordon", "Gene Ammons", "Zoot Sims", "Gerry Mulligan", "Art Pepper", "Lou Donaldson", "Johnny Hodges", "Hank Mobley", "Sonny Rollins", "Benny Golson"],
  "Lester Young": ["Coleman Hawkins", "Ben Webster", "Zoot Sims", "Dexter Gordon", "Gene Ammons", "Johnny Hodges", "Gerry Mulligan", "J.J. Johnson", "Oscar Peterson", "Sonny Stitt", "Cannonball Adderley", "Art Pepper"],
  "Ben Webster": ["Coleman Hawkins", "Gene Ammons", "Gerry Mulligan", "Lester Young", "Johnny Hodges", "Dexter Gordon", "Zoot Sims", "Benny Golson", "Houston Person", "Art Pepper", "Oscar Peterson", "Kenny Burrell"],
  "Don Byas": ["Johnny Hodges", "Coleman Hawkins", "Sonny Criss", "Lucky Thompson", "Illinois Jacquet", "Zoot Sims", "Lester Young", "Clark Terry", "Lionel Hampton", "Gene Ammons", "Gerry Mulligan", "Ben Webster"],
  "Illinois Jacquet": ["Gene Ammons", "Johnny Hodges", "Coleman Hawkins", "Eddie Lockjaw Davis", "Clark Terry", "Sonny Stitt", "Count Basie", "Ben Webster", "Lester Young", "Zoot Sims", "Don Byas", "Lionel Hampton"],
  "Arnett Cobb": ["Wardell Gray", "Al Cohn", "Paul Gonsalves", "Bennie Green", "Cecil Payne", "Frank Wess", "Buck Clayton", "Pepper Adams", "George Coleman", "Coleman Hawkins", "Gene Ammons", "Terry Gibbs"],
  "Lucky Thompson": ["Johnny Griffin", "Don Byas", "Hank Mobley", "Zoot Sims", "Gene Ammons", "Coleman Hawkins", "Art Farmer", "Sonny Stitt", "Sonny Criss", "Stanley Turrentine", "Booker Ervin", "Benny Golson"],
  "Budd Johnson": ["Arnett Cobb", "Paul Gonsalves", "Buck Clayton", "Frank Wess", "Al Cohn", "Wardell Gray", "Johnny Dodds", "Edmond Hall", "Cootie Williams", "Cecil Payne", "Pee Wee Russell", "Lester Young"],
  "Dexter Gordon": ["Hank Mobley", "Lee Morgan", "Sonny Rollins", "Freddie Hubbard", "Sonny Clark", "Cannonball Adderley", "Art Pepper", "Jackie McLean", "Joe Henderson", "Horace Silver", "Coleman Hawkins", "Kenny Dorham"],
  "Wardell Gray": ["Ruby Braff", "Paul Gonsalves", "Arnett Cobb", "Al Cohn", "Bennie Green", "Pepper Adams", "Cecil Payne", "Frank Rosolino", "Al Haig", "Kenny Clarke", "Buck Clayton", "Pee Wee Russell"],
  "Gene Ammons": ["Coleman Hawkins", "Sonny Stitt", "Ben Webster", "Dexter Gordon", "Zoot Sims", "Benny Golson", "Johnny Hodges", "Stanley Turrentine", "Lou Donaldson", "Art Pepper", "Illinois Jacquet", "Hank Mobley"],
  "Sonny Stitt": ["Gene Ammons", "Dexter Gordon", "Sonny Rollins", "Johnny Griffin", "Art Pepper", "Cannonball Adderley", "Johnny Hodges", "Charlie Parker", "Hank Mobley", "Zoot Sims", "Dizzy Gillespie", "Coleman Hawkins"],
  "Sonny Rollins": ["Dexter Gordon", "Cannonball Adderley", "Hank Mobley", "Lee Morgan", "Wayne Shorter", "Jackie McLean", "Joe Henderson", "John Coltrane", "Freddie Hubbard", "Art Pepper", "Kenny Burrell", "Miles Davis"],
  "John Coltrane": ["Miles Davis", "Wayne Shorter", "Charles Mingus", "Cannonball Adderley", "Sonny Rollins", "Thelonious Monk", "Ornette Coleman", "McCoy Tyner", "Eric Dolphy", "Lee Morgan", "Joe Henderson", "Dexter Gordon"],
  "Hank Mobley": ["Lee Morgan", "Dexter Gordon", "Horace Silver", "Sonny Clark", "Jackie McLean", "Freddie Hubbard", "Stanley Turrentine", "Lou Donaldson", "Sonny Rollins", "Kenny Dorham", "Cannonball Adderley", "Joe Henderson"],
  "Johnny Griffin": ["Jackie McLean", "Hank Mobley", "Lou Donaldson", "Sonny Clark", "Sonny Stitt", "Dexter Gordon", "Lee Morgan", "Booker Ervin", "Stanley Turrentine", "Sonny Rollins", "Eddie Lockjaw Davis", "Benny Golson"],
  "Eddie Lockjaw Davis": ["Johnny Griffin", "Gene Ammons", "Illinois Jacquet", "Blue Mitchell", "Booker Ervin", "Milt Jackson", "Jackie McLean", "Sonny Stitt", "Red Garland", "Lou Donaldson", "Stanley Turrentine", "Zoot Sims"],
  "Stanley Turrentine": ["Lou Donaldson", "Hank Mobley", "Freddie Hubbard", "Jackie McLean", "Lee Morgan", "Dexter Gordon", "Jimmy Smith", "Horace Parlan", "Donald Byrd", "Horace Silver", "Kenny Burrell", "Sonny Clark"],
  "Booker Ervin": ["Jackie McLean", "Andrew Hill", "Elvin Jones", "Joe Henderson", "Johnny Griffin", "Lee Morgan", "Horace Parlan", "Hank Mobley", "Woody Shaw", "Harold Land", "Freddie Hubbard", "Wayne Shorter"],
  "Joe Henderson": ["Wayne Shorter", "Lee Morgan", "Freddie Hubbard", "Jackie McLean", "McCoy Tyner", "Hank Mobley", "Woody Shaw", "Dexter Gordon", "Sonny Rollins", "Andrew Hill", "Bobby Hutcherson", "Cannonball Adderley"],
  "Wayne Shorter": ["Joe Henderson", "Lee Morgan", "Freddie Hubbard", "McCoy Tyner", "John Coltrane", "Sonny Rollins", "Hank Mobley", "Herbie Hancock", "Cannonball Adderley", "Miles Davis", "Jackie McLean", "Dexter Gordon"],
  "Clifford Jordan": ["Jackie McLean", "Charlie Rouse", "Hank Mobley", "Stanley Turrentine", "Joe Henderson", "Booker Ervin", "Horace Parlan", "Andrew Hill", "Harold Land", "Sonny Criss", "Lee Morgan", "Kenny Dorham"],
  "Harold Land": ["Jackie McLean", "Booker Ervin", "Horace Parlan", "Sonny Criss", "Nat Adderley", "Joe Henderson", "Johnny Griffin", "Dexter Gordon", "Cannonball Adderley", "Clifford Jordan", "Hank Mobley", "Lee Morgan"],
  "Teddy Edwards": ["Stanley Turrentine", "Dexter Gordon", "Hank Mobley", "Joe Henderson", "Lee Morgan", "Gene Ammons", "Sonny Rollins", "Jackie McLean", "Houston Person", "Freddie Hubbard", "Cannonball Adderley", "Horace Parlan"],
  "Jimmy Heath": ["Jackie McLean", "Nat Adderley", "Joe Henderson", "Gene Ammons", "Woody Shaw", "Joe Lovano", "Immanuel Wilkins", "Booker Ervin", "Teddy Edwards", "Dexter Gordon", "Eddie Lockjaw Davis", "Johnny Griffin"],
  "Benny Golson": ["Sonny Clark", "Art Farmer", "Hank Mobley", "Gene Ammons", "Dexter Gordon", "Ben Webster", "Coleman Hawkins", "Johnny Griffin", "Kenny Dorham", "Red Garland", "Gerry Mulligan", "Curtis Fuller"],
  "George Coleman": ["Vincent Herring", "Pepper Adams", "Jimmy Cobb", "Dave Liebman", "Arnett Cobb", "Seamus Blake", "Ravi Coltrane", "Al Cohn", "Bobby Watson", "Bob Berg", "Paul Gonsalves", "Ernie Watts"],
  "Charlie Rouse": ["Clifford Jordan", "Benny Golson", "Johnny Griffin", "Hank Mobley", "Sonny Stitt", "Joe Henderson", "Jackie McLean", "Sonny Criss", "Les McCann", "Johnny Hodges", "Harold Land", "Elvin Jones"],
  "Yusef Lateef": ["Pharoah Sanders", "Joe Henderson", "Wayne Shorter", "Lee Morgan", "McCoy Tyner", "Eric Dolphy", "Freddie Hubbard", "Bobby Hutcherson", "John Coltrane", "Charles Mingus", "Max Roach", "Kenny Dorham"],
  "Paul Gonsalves": ["Wardell Gray", "Harry Edison", "Al Cohn", "Pepper Adams", "Arnett Cobb", "Herb Geller", "Buck Clayton", "Frank Wess", "Vincent Herring", "Von Freeman", "Pee Wee Russell"],
  "Frank Foster": ["Frank Wess", "Bennie Green", "Vincent Herring", "George Coleman", "Cecil Payne", "Arnett Cobb", "Al Cohn", "Bob Berg", "Bobby Watson", "Greg Osby", "Ravi Coltrane", "Paul Gonsalves"],
  "Frank Wess": ["Cecil Payne", "Carl Fontana", "Arnett Cobb", "Al Cohn", "Bennie Green", "Slide Hampton", "Red Mitchell", "Paul Gonsalves", "Wardell Gray", "Pepper Adams", "Frank Foster", "Kenny Clarke"],
  "Zoot Sims": ["Coleman Hawkins", "Gene Ammons", "Lester Young", "Ben Webster", "Art Farmer", "Gerry Mulligan", "Sonny Stitt", "Art Pepper", "Lee Konitz", "Bud Shank", "Johnny Hodges", "Houston Person"],
  "Al Cohn": ["Paul Gonsalves", "Terry Gibbs", "Wardell Gray", "Arnett Cobb", "Ruby Braff", "Bennie Green", "Frank Wess", "Pepper Adams", "Cecil Payne", "Herb Geller", "Charlie Mariano", "Buck Clayton"],
  "Stan Getz": ["Paul Desmond", "Gerry Mulligan", "Coleman Hawkins", "Ben Webster", "Cannonball Adderley", "Chet Baker", "Art Pepper", "Sonny Rollins", "Kenny Burrell", "Lester Young", "Bill Evans", "Dexter Gordon"],
  "Archie Shepp": ["Albert Ayler", "Andrew Hill", "Ornette Coleman", "Eric Dolphy", "Pharoah Sanders", "Don Cherry", "Cecil Taylor", "Marion Brown", "Elvin Jones", "David Murray", "Joe Henderson", "John Coltrane"],
  "Pharoah Sanders": ["Don Cherry", "Archie Shepp", "Ornette Coleman", "Albert Ayler", "John Coltrane", "Yusef Lateef", "Eric Dolphy", "Joe Henderson", "Andrew Hill", "Charles Mingus", "McCoy Tyner", "Wayne Shorter"],
  "Albert Ayler": ["Cecil Taylor", "Ornette Coleman", "Eric Dolphy", "Archie Shepp", "Don Cherry", "Andrew Hill", "Marion Brown", "Pharoah Sanders", "John Coltrane", "Grachan Moncur III", "Larry Young", "Jackie McLean"],
  "Charles Lloyd": ["Joshua Redman", "John Abercrombie", "Joe Lovano", "Keith Jarrett", "Paul Motian", "Enrico Rava", "Christian McBride", "Bill Frisell", "Chris Potter", "Brad Mehldau", "Dave Holland", "Bobo Stenson"],
  "Dewey Redman": ["Muhal Richard Abrams", "Tim Berne", "Sunny Murray", "Milford Graves", "Greg Osby", "Don Pullen", "Andrew Cyrille", "Steve Coleman", "Hamiet Bluiett", "Rudresh Mahanthappa", "Roswell Rudd", "Steve Lehman"],
  "David Murray": ["Archie Shepp", "Andrew Hill", "Ornette Coleman", "Eric Dolphy", "Marion Brown", "Cecil Taylor", "Jackie McLean", "Albert Ayler", "Vijay Iyer", "Don Cherry", "Elvin Jones", "Dave Holland"],
  "Von Freeman": ["Jimmy Cobb", "Paul Gonsalves", "Ravi Coltrane", "Cecil Payne", "Seamus Blake", "Greg Osby", "Bob Berg", "Dave Liebman", "Vincent Herring", "Pepper Adams", "Bob Mintzer", "Ernie Watts"],
  "Houston Person": ["Ben Webster", "Red Garland", "Jimmy Raney", "Stanley Turrentine", "Kenny Burrell", "Coleman Hawkins", "Zoot Sims", "Gene Ammons", "Wynton Marsalis", "Art Pepper", "Sonny Stitt", "Lou Donaldson"],
  "Michael Brecker": ["Joshua Redman", "Kenny Garrett", "Wayne Shorter", "Chris Potter", "Pat Metheny", "Joe Henderson", "Mike Stern", "John Scofield", "John Abercrombie", "Chick Corea", "Branford Marsalis", "John Patitucci"],
  "Bob Berg": ["Marcus Gilmore", "Randy Brecker", "Seamus Blake", "Bob Mintzer", "Ravi Coltrane", "Jeff Tain Watts", "Greg Osby", "Dave Liebman"],
  "Bob Mintzer": ["Bob Berg", "Randy Brecker", "Ernie Watts", "Ravi Coltrane", "Seamus Blake", "Bill Watrous", "Greg Osby", "Dave Liebman", "Conrad Herwig", "George Coleman", "Vincent Herring"],
  "Ernie Watts": ["Bob Mintzer", "Bob Berg", "Charlie Mariano", "Greg Osby", "Dave Liebman", "Ravi Coltrane", "Vincent Herring", "Randy Brecker", "George Coleman", "Al Cohn", "Seamus Blake", "Paul Gonsalves"],
  "Joe Lovano": ["Mark Turner", "Walter Smith III", "Joe Henderson", "Joshua Redman", "Charles Lloyd", "Miroslav Vitous", "John Scofield", "Charlie Haden", "Bobo Stenson", "Immanuel Wilkins", "Enrico Rava", "Vijay Iyer"],
  "Branford Marsalis": ["Joshua Redman", "Walter Smith III", "Kenny Garrett", "Joe Lovano", "Michael Brecker", "Joe Henderson", "Wynton Marsalis", "Mark Turner", "Roy Hargrove", "Chris Potter", "Charles Lloyd", "Christian McBride"],
  "Joshua Redman": ["Chris Potter", "Michael Brecker", "Christian McBride", "Brad Mehldau", "Kenny Garrett", "John Scofield", "Charles Lloyd", "Joe Lovano", "Wayne Shorter", "Roy Hargrove", "Branford Marsalis", "Fred Hersch"],
  "Chris Potter": ["Joshua Redman", "Kenny Garrett", "Walter Smith III", "Ambrose Akinmusire", "Mark Turner", "Michael Brecker", "Charles Lloyd", "Peter Bernstein", "Immanuel Wilkins", "Christian McBride", "Dave Holland", "Joe Lovano"],
  "Mark Turner": ["Joe Lovano", "Walter Smith III", "Kurt Rosenwinkel", "Chris Potter", "Dave Douglas", "Miroslav Vitous", "Vijay Iyer", "Craig Taborn", "Joshua Redman", "Immanuel Wilkins", "Paul Motian", "Linda May Han Oh"],
  "Ravi Coltrane": ["Greg Osby", "Bob Berg", "Rudresh Mahanthappa", "Steve Coleman", "Seamus Blake", "Dave Liebman", "Jeff Tain Watts", "Steve Lehman", "Marcus Gilmore", "Tim Berne", "Stefon Harris", "Dewey Redman"],
  "Seamus Blake": ["Marcus Gilmore", "Bob Berg", "Lage Lund", "Greg Osby", "Bill Stewart", "Ravi Coltrane", "Dave Liebman", "Vincent Herring", "Eric Harland"],
  "Melissa Aldana": ["Walter Smith III", "Sullivan Fortner", "Immanuel Wilkins", "Aaron Parks", "Mark Turner", "Charles Lloyd", "Joshua Redman", "Joe Lovano", "Chris Potter", "Kenny Barron", "Gerald Clayton", "Joe Henderson"],
  "Kamasi Washington": ["Nubya Garcia", "Ambrose Akinmusire", "Robert Glasper", "Pharoah Sanders", "Esperanza Spalding", "Makaya McCraven", "Hiromi", "Charles Mingus", "Herbie Hancock", "Joe Henderson", "Wayne Shorter", "John Coltrane"],
  "Walter Smith III": ["Immanuel Wilkins", "Kurt Rosenwinkel", "Mark Turner", "Joe Lovano", "Joe Henderson", "Marquis Hill", "Melissa Aldana", "Chris Potter", "Gilad Hekselman", "Kenny Garrett", "Wayne Shorter", "Branford Marsalis"],
  "Shabaka Hutchings": ["Nubya Garcia", "Art Pepper", "Makaya McCraven", "Bill Frisell", "Marquis Hill", "Ambrose Akinmusire", "Kamasi Washington", "Sonny Rollins", "Immanuel Wilkins"],
  "Nubya Garcia": ["Makaya McCraven", "Kamasi Washington", "Immanuel Wilkins", "Robert Glasper", "Charles Lloyd", "Ambrose Akinmusire", "Joshua Redman"],
  "Johnny Hodges": ["Ben Webster", "Gene Ammons", "Coleman Hawkins", "Sonny Stitt", "Gerry Mulligan", "Illinois Jacquet", "Lester Young", "Zoot Sims", "Don Byas", "Benny Golson", "Hank Mobley", "Red Garland"],
  "Benny Carter": ["Coleman Hawkins", "Teddy Wilson", "Ben Webster", "Zoot Sims", "Lester Young", "Illinois Jacquet", "Earl Hines", "Gene Ammons", "Johnny Hodges", "Benny Goodman", "Count Basie", "Lou Donaldson"],
  "Willie Smith": ["Jimmie Noone", "Frank Foster", "James Williams", "Arnett Cobb", "Al Cohn", "Wardell Gray", "Buck Clayton"],
  "Charlie Parker": ["Dizzy Gillespie", "Bud Powell", "John Coltrane", "Thelonious Monk", "Clifford Brown", "Sonny Rollins", "Dexter Gordon", "Cannonball Adderley", "Miles Davis", "Sonny Stitt", "Wayne Shorter", "Coleman Hawkins"],
  "Sonny Criss": ["Tal Farlow", "Stanley Turrentine", "Benny Golson", "Nat Adderley", "Sonny Rollins", "Jackie McLean", "Sonny Stitt", "Harold Land", "Johnny Griffin", "Hank Mobley", "Cannonball Adderley", "Lee Morgan"],
  "Frank Morgan": ["Art Pepper", "Dexter Gordon", "Ron Carter", "Gene Ammons", "Hank Mobley", "Kenny Dorham", "Stanley Turrentine", "Sonny Clark", "Coleman Hawkins", "Clifford Brown", "Red Garland", "Sonny Rollins"],
  "Jackie McLean": ["Hank Mobley", "Lee Morgan", "Andrew Hill", "Booker Ervin", "Joe Henderson", "Horace Parlan", "Freddie Hubbard", "Dexter Gordon", "Stanley Turrentine", "Lou Donaldson", "Sonny Rollins", "Bobby Hutcherson"],
  "Lou Donaldson": ["Stanley Turrentine", "Hank Mobley", "Jackie McLean", "Lee Morgan", "Dexter Gordon", "Blue Mitchell", "Sonny Clark", "Jimmy Smith", "Donald Byrd", "Jimmy McGriff", "Horace Silver", "Grant Green"],
  "Cannonball Adderley": ["Sonny Rollins", "Lee Morgan", "Dexter Gordon", "Hank Mobley", "Wayne Shorter", "Art Pepper", "Freddie Hubbard", "Kenny Burrell", "John Coltrane", "Miles Davis", "Joe Henderson", "Horace Silver"],
  "Phil Woods": ["Cannonball Adderley", "Hank Mobley", "Sonny Stitt", "Jackie McLean", "Dexter Gordon", "Art Pepper", "Johnny Griffin", "Stanley Turrentine", "J.J. Johnson", "Eddie Lockjaw Davis", "Sonny Criss", "Joe Henderson"],
  "Art Pepper": ["Dexter Gordon", "Cannonball Adderley", "Gerry Mulligan", "Hank Mobley", "Sonny Rollins", "Frank Morgan", "Lee Konitz", "Kenny Burrell", "Coleman Hawkins", "Lee Morgan", "Sonny Clark", "Sonny Stitt"],
  "Lee Konitz": ["Art Pepper", "Gerry Mulligan", "Jimmy Giuffre", "Paul Desmond", "Sonny Stitt", "Jackie McLean", "Sonny Rollins", "Shorty Rogers", "Art Farmer", "Dexter Gordon", "Cannonball Adderley", "Zoot Sims"],
  "Paul Desmond": ["Stan Getz", "Gerry Mulligan", "Lee Konitz", "Jim Hall", "Bill Evans", "Coleman Hawkins", "Art Pepper", "Chet Baker", "Cannonball Adderley", "Wes Montgomery", "Ben Webster", "Zoot Sims"],
  "Bud Shank": ["Zoot Sims", "Shelly Manne", "Jimmy Giuffre", "Gerry Mulligan", "Lee Konitz", "Paul Desmond", "George Shearing", "Art Pepper", "Stanley Turrentine", "Coleman Hawkins", "Cal Tjader", "Houston Person"],
  "Herb Geller": ["Conte Candoli", "Terry Gibbs", "Al Cohn", "Paul Gonsalves", "Charlie Mariano", "Frank Rosolino", "Wardell Gray", "Arnett Cobb", "Jimmy Cobb", "Pepper Adams", "Ruby Braff", "Leroy Vinnegar"],
  "Charlie Mariano": ["Albert Mangelsdorff", "Dave Liebman", "Ernie Watts", "Al Cohn", "Greg Osby", "Cecil Payne", "Herb Geller", "Wardell Gray", "Ravi Coltrane", "Frank Rosolino", "Arnett Cobb", "Rudresh Mahanthappa"],
  "Hank Crawford": ["Gene Ammons", "Stanley Turrentine", "Coleman Hawkins", "Lou Donaldson", "Sonny Stitt", "Lester Young", "Zoot Sims", "Bobbi Humphrey", "Clark Terry", "Charles Earland", "Donald Byrd", "Jackie McLean"],
  "Ornette Coleman": ["Eric Dolphy", "Cecil Taylor", "Albert Ayler", "John Coltrane", "Andrew Hill", "Wayne Shorter", "Don Cherry", "Archie Shepp", "Charles Mingus", "Marion Brown", "Pharoah Sanders", "Jackie McLean"],
  "Eric Dolphy": ["Andrew Hill", "Ornette Coleman", "Albert Ayler", "Cecil Taylor", "John Coltrane", "Jackie McLean", "Grachan Moncur III", "Wayne Shorter", "Charles Mingus", "Joe Henderson", "Archie Shepp", "Max Roach"],
  "Marion Brown": ["Cecil Taylor", "Ornette Coleman", "Albert Ayler", "Archie Shepp", "Don Cherry", "Lee Konitz", "Andrew Hill", "Eric Dolphy", "Grachan Moncur III", "Jimmy Giuffre", "David Murray", "Pharoah Sanders"],
  "Gary Bartz": ["Charles Earland", "Bobbi Humphrey", "Donald Byrd", "Roy Ayers", "Herbie Hancock", "Gene Harris", "Joe Henderson", "Dizzy Gillespie", "Pharoah Sanders", "Woody Shaw", "Ramsey Lewis", "Jack McDuff"],
  "David Sanborn": ["Joe Sample", "George Benson", "Marcus Miller", "Pat Metheny"],
  "Bobby Watson": ["Vincent Herring", "Dave Liebman", "Steve Turre", "George Coleman", "Greg Osby", "Seamus Blake", "Joe Locke", "Ravi Coltrane", "Gary Smulyan", "Paul Gonsalves", "Bob Mintzer"],
  "Kenny Garrett": ["Chris Potter", "Joshua Redman", "Michael Brecker", "Roy Hargrove", "Joe Henderson", "Walter Smith III", "Branford Marsalis", "Immanuel Wilkins", "Cedar Walton", "Mark Turner", "Wayne Shorter", "Kurt Rosenwinkel"],
  "Steve Coleman": ["Greg Osby", "Tim Berne", "Steve Lehman", "Rudresh Mahanthappa", "Ravi Coltrane", "Muhal Richard Abrams", "Dave Liebman", "Dewey Redman", "Jeff Tain Watts", "Don Pullen", "Seamus Blake", "Billy Hart"],
  "Greg Osby": ["Steve Coleman", "Tim Berne", "Ravi Coltrane", "Jeff Tain Watts", "Stefon Harris", "Dewey Redman", "Steve Lehman", "Rudresh Mahanthappa", "Seamus Blake", "Dave Liebman", "Danilo Perez", "Muhal Richard Abrams"],
  "John Zorn": ["Ornette Coleman", "Bill Frisell", "Albert Ayler", "Mary Halvorson", "Eric Dolphy", "Cecil Taylor", "Don Cherry", "Archie Shepp", "Charles Mingus", "Andrew Hill", "Pharoah Sanders", "John Coltrane"],
  "Tim Berne": ["Muhal Richard Abrams", "Dewey Redman", "Greg Osby", "Steve Coleman", "Milford Graves", "Steve Lehman", "Sunny Murray", "Rudresh Mahanthappa"],
  "Vincent Herring": ["Bobby Watson", "Dave Liebman", "George Coleman", "Seamus Blake", "Jimmy Cobb", "Bob Berg"],
  "Rudresh Mahanthappa": ["Steve Lehman", "Tim Berne", "Steve Coleman", "Greg Osby", "Ravi Coltrane", "Dave Liebman", "Dewey Redman", "Muhal Richard Abrams", "Billy Hart", "Eric Harland", "Seamus Blake"],
  "Miguel Zenon": ["Walter Smith III", "Immanuel Wilkins", "Kurt Rosenwinkel", "Joshua Redman", "Branford Marsalis", "Kenny Garrett", "Charles Lloyd", "Melissa Aldana", "Ambrose Akinmusire", "Chris Potter", "Joe Lovano", "Gerald Clayton"],
  "Steve Lehman": ["Rudresh Mahanthappa", "Tim Berne", "Steve Coleman", "Greg Osby", "Ravi Coltrane", "Muhal Richard Abrams", "Dave Liebman", "Dewey Redman", "Eric Harland", "Seamus Blake"],
  "Immanuel Wilkins": ["Walter Smith III", "Ambrose Akinmusire", "Gerald Clayton", "Chris Potter", "Aaron Parks", "Joe Lovano", "Charles Lloyd", "Kenny Garrett", "Mark Turner", "Wayne Shorter", "Melissa Aldana", "Kurt Rosenwinkel"],
  "Lakecia Benjamin": ["Terri Lyne Carrington", "Immanuel Wilkins", "Cecile McLorin Salvant", "Chris Potter", "Linda May Han Oh", "Joey Alexander", "Melissa Aldana", "Ambrose Akinmusire", "Steve Swallow", "Joe Lovano", "Joshua Redman", "Mark Turner"],
  "Sidney Bechet": ["Benny Goodman", "Earl Hines", "Lionel Hampton", "Louis Armstrong", "Fats Waller", "Coleman Hawkins", "Johnny Hodges", "Bix Beiderbecke", "Lester Young", "Django Reinhardt", "Jelly Roll Morton", "Count Basie"],
  "Dave Liebman": ["Greg Osby", "Vincent Herring", "Ravi Coltrane", "Seamus Blake", "Rudresh Mahanthappa", "Steve Coleman", "Bobby Watson", "Bob Berg", "Steve Lehman", "Tim Berne", "Dewey Redman", "Jeff Tain Watts"],
  "Jane Ira Bloom": ["Rudresh Mahanthappa", "Dave Liebman", "Greg Osby", "Seamus Blake", "Don Pullen", "Ravi Coltrane", "Charlie Mariano", "George Coleman", "Andrew Cyrille", "Tim Berne", "Charles Lloyd", "Hamiet Bluiett"],
  "Harry Carney": ["Barney Bigard", "Paul Gonsalves", "Sid Catlett", "Lawrence Brown", "Harry Edison", "Arnett Cobb", "Pee Wee Russell", "Cootie Williams", "Buck Clayton"],
  "Serge Chaloff": ["Lee Konitz", "Jackie McLean", "Shorty Rogers", "Gerry Mulligan", "Art Pepper", "Hank Mobley", "Jimmy Giuffre", "Bob Brookmeyer", "Lou Donaldson", "Johnny Griffin", "Eddie Lockjaw Davis", "Illinois Jacquet"],
  "Gerry Mulligan": ["Art Pepper", "Coleman Hawkins", "Ben Webster", "Lee Konitz", "Paul Desmond", "Dexter Gordon", "Johnny Hodges", "Zoot Sims", "Cannonball Adderley", "Stan Getz", "Benny Golson", "Chet Baker"],
  "Pepper Adams": ["Paul Gonsalves", "Ronnie Cuber", "Wardell Gray", "Al Cohn", "Cecil Payne", "Gary Smulyan", "Arnett Cobb", "Vincent Herring", "George Coleman", "Frank Wess", "Herb Geller", "Von Freeman"],
  "Cecil Payne": ["Carl Fontana", "Frank Wess", "Frank Rosolino", "Bennie Green", "Arnett Cobb", "Wardell Gray", "Ronnie Cuber", "Red Mitchell", "Pepper Adams", "Al Haig", "Al Cohn", "Conte Candoli"],
  "Ronnie Cuber": ["Gary Smulyan", "Pepper Adams", "Cecil Payne", "Vincent Herring", "Bob Berg", "Wardell Gray", "George Coleman", "Paul Gonsalves", "Arnett Cobb", "Seamus Blake", "Bob Mintzer", "Mel Lewis"],
  "Hamiet Bluiett": ["Muhal Richard Abrams", "Billy Bang", "Dewey Redman", "Don Pullen", "Sunny Murray", "Tim Berne", "Cecil McBee", "Andrew Cyrille", "Rudresh Mahanthappa"],
  "Gary Smulyan": ["Ronnie Cuber", "Pepper Adams", "Cecil Payne", "Vincent Herring", "Bobby Watson", "Wycliffe Gordon", "Jimmy Cobb", "Bob Mintzer", "Bob Berg", "George Coleman", "Paul Gonsalves", "Von Freeman"],
  "Jack Teagarden": ["Artie Shaw", "Chick Webb", "Duke Ellington", "Benny Goodman", "Lionel Hampton", "J.J. Johnson", "Roy Eldridge", "Gene Krupa", "Bix Beiderbecke", "Count Basie", "Fats Waller", "Coleman Hawkins"],
  "Vic Dickenson": ["Ruby Braff", "Buck Clayton", "Urbie Green", "Frank Rosolino", "Carl Fontana", "Slide Hampton", "Bennie Green", "Steve Turre", "Jo Jones", "Wycliffe Gordon", "Conrad Herwig", "Bill Watrous"],
  "Lawrence Brown": ["Frank Rosolino", "Harry Edison", "Carl Fontana", "Wycliffe Gordon", "Slide Hampton", "Harry Carney", "Buck Clayton", "Bill Watrous", "Bennie Green", "Bobby Hackett", "Paul Gonsalves", "Cootie Williams"],
  "Tommy Dorsey": ["Artie Shaw", "Benny Goodman", "Gene Krupa", "Chick Webb", "Fats Waller", "Count Basie", "Lionel Hampton", "Louis Armstrong", "Teddy Wilson", "Bix Beiderbecke", "Sidney Bechet", "Duke Ellington"],
  "J.J. Johnson": ["Curtis Fuller", "Kai Winding", "Thad Jones", "Clifford Brown", "Dexter Gordon", "Lester Young", "Sonny Stitt", "Dizzy Gillespie", "Cannonball Adderley", "Sonny Rollins", "Bob Brookmeyer", "Jackie McLean"],
  "Kai Winding": ["J.J. Johnson", "Curtis Fuller", "Dizzy Gillespie", "Thad Jones", "Sonny Stitt", "Freddie Hubbard", "Charlie Parker", "Sonny Criss", "Dexter Gordon", "Milt Jackson", "Nat Adderley", "Bob Brookmeyer"],
  "Bennie Green": ["Frank Rosolino", "Slide Hampton", "Al Haig", "Urbie Green", "Carl Fontana", "Arnett Cobb", "Wardell Gray", "Cecil Payne", "Al Cohn", "Frank Wess", "Kenny Clarke", "Steve Turre"],
  "Curtis Fuller": ["J.J. Johnson", "Sonny Clark", "Hank Mobley", "Lee Morgan", "Blue Mitchell", "Benny Golson", "Dexter Gordon", "Horace Silver", "Freddie Hubbard", "Jackie McLean", "Hank Jones", "Kenny Dorham"],
  "Slide Hampton": ["Frank Rosolino", "Carl Fontana", "Bill Watrous", "Wycliffe Gordon", "Conrad Herwig", "Urbie Green", "Steve Turre", "Ray Anderson", "Bennie Green", "Albert Mangelsdorff", "Frank Wess", "Ruby Braff"],
  "Jimmy Knepper": ["Frank Rosolino", "Conrad Herwig", "Bill Watrous", "Slide Hampton", "Steve Turre", "Carl Fontana", "Urbie Green", "Wycliffe Gordon", "Bennie Green", "Ray Anderson", "Albert Mangelsdorff", "Pepper Adams"],
  "Bob Brookmeyer": ["Gerry Mulligan", "J.J. Johnson", "Zoot Sims", "Curtis Fuller", "Hank Mobley", "Serge Chaloff", "Bill Evans", "Milt Jackson", "Paul Desmond", "Stan Getz", "Thad Jones", "Lee Konitz"],
  "Frank Rosolino": ["Carl Fontana", "Slide Hampton", "Bill Watrous", "Steve Turre", "Wycliffe Gordon", "Urbie Green", "Conrad Herwig", "Bennie Green", "Ray Anderson", "Terry Gibbs", "Cecil Payne", "Mel Lewis"],
  "Carl Fontana": ["Frank Rosolino", "Slide Hampton", "Bill Watrous", "Urbie Green", "Steve Turre", "Wycliffe Gordon", "Conrad Herwig", "Cecil Payne", "Ray Anderson", "Bennie Green", "Frank Wess", "Red Mitchell"],
  "Urbie Green": ["Carl Fontana", "Frank Rosolino", "Bill Watrous", "Slide Hampton", "Wycliffe Gordon", "Steve Turre", "Conrad Herwig", "Bennie Green", "Ray Anderson", "Vic Dickenson", "Albert Mangelsdorff", "J.J. Johnson"],
  "Bill Watrous": ["Frank Rosolino", "Carl Fontana", "Wycliffe Gordon", "Slide Hampton", "Urbie Green", "Steve Turre", "Conrad Herwig", "Ray Anderson", "Bob Mintzer", "Bennie Green"],
  "Grachan Moncur III": ["Andrew Hill", "Jackie McLean", "Eric Dolphy", "Bobby Hutcherson", "Stanley Turrentine", "Cecil Taylor", "Ornette Coleman", "Archie Shepp", "Joe Henderson", "Marion Brown", "Freddie Hubbard", "McCoy Tyner"],
  "Roswell Rudd": ["Muhal Richard Abrams", "Dewey Redman", "Albert Mangelsdorff", "Sunny Murray", "Steve Turre", "Tim Berne", "Milford Graves", "Frank Rosolino", "Andrew Cyrille", "Don Pullen", "Billy Bang", "Steve Lehman"],
  "Albert Mangelsdorff": ["Ray Anderson", "Frank Rosolino", "Slide Hampton", "Roswell Rudd", "Steve Turre", "Conrad Herwig", "Charlie Mariano", "Dewey Redman", "Tim Berne", "Andrew Cyrille", "Urbie Green", "Muhal Richard Abrams"],
  "Ray Anderson": ["Slide Hampton", "Frank Rosolino", "Steve Turre", "Conrad Herwig", "Carl Fontana", "Albert Mangelsdorff", "Bill Watrous", "Urbie Green", "Wycliffe Gordon", "Roswell Rudd", "Bennie Green", "Jimmy Knepper"],
  "Steve Turre": ["Frank Rosolino", "Conrad Herwig", "Carl Fontana", "Slide Hampton", "Bill Watrous", "Wycliffe Gordon", "Urbie Green", "Ray Anderson", "Joe Locke", "Bennie Green", "Albert Mangelsdorff", "Roswell Rudd"],
  "Robin Eubanks": ["Steve Turre", "Slide Hampton", "Conrad Herwig", "Frank Rosolino", "Bill Watrous", "Ray Anderson", "Wycliffe Gordon", "Urbie Green", "Albert Mangelsdorff", "Carl Fontana", "Bennie Green", "Jimmy Knepper"],
  "Wycliffe Gordon": ["Bill Watrous", "Frank Rosolino", "Slide Hampton", "Carl Fontana", "Conrad Herwig", "Steve Turre", "Urbie Green", "Bennie Green", "Ray Anderson", "Albert Mangelsdorff", "Mel Lewis", "Jimmy Knepper"],
  "Conrad Herwig": ["Frank Rosolino", "Steve Turre", "Slide Hampton", "Carl Fontana", "Wycliffe Gordon", "Bill Watrous", "Ray Anderson", "Urbie Green", "Albert Mangelsdorff", "Bennie Green", "Jeff Tain Watts", "Jimmy Knepper"],
  "Jelly Roll Morton": ["James P. Johnson", "Bix Beiderbecke", "Fats Waller", "Duke Ellington", "Sidney Bechet", "Louis Armstrong", "Earl Hines", "Johnny Hodges", "Count Basie", "Art Tatum", "Wynton Kelly", "Ahmad Jamal"],
  "James P. Johnson": ["Jelly Roll Morton", "Earl Hines", "Fats Waller", "Art Tatum", "Teddy Wilson", "Erroll Garner", "Duke Ellington", "Hank Jones", "Count Basie", "George Shearing", "Bud Powell", "Keith Jarrett"],
  "Fats Waller": ["Count Basie", "Earl Hines", "James P. Johnson", "Jelly Roll Morton", "Lionel Hampton", "Bix Beiderbecke", "Benny Goodman", "Art Tatum", "Sidney Bechet", "Artie Shaw", "Louis Armstrong", "Erroll Garner"],
  "Earl Hines": ["Teddy Wilson", "James P. Johnson", "Art Tatum", "Fats Waller", "Count Basie", "Roy Eldridge", "Erroll Garner", "Sidney Bechet", "Duke Ellington", "Oscar Peterson", "Lionel Hampton", "George Shearing"],
  "Art Tatum": ["Erroll Garner", "Earl Hines", "Oscar Peterson", "Bud Powell", "Duke Ellington", "Teddy Wilson", "Fats Waller", "Count Basie", "Thelonious Monk", "George Shearing", "Hank Jones", "McCoy Tyner"],
  "Teddy Wilson": ["Earl Hines", "Hank Jones", "Benny Carter", "Art Tatum", "Erroll Garner", "Duke Ellington", "Count Basie", "James P. Johnson", "Tommy Flanagan", "Oscar Peterson", "Fats Waller", "Red Garland"],
  "Duke Ellington": ["Count Basie", "Benny Goodman", "Charlie Parker", "Thelonious Monk", "Louis Armstrong", "Miles Davis", "Coleman Hawkins", "Charles Mingus", "Art Tatum", "Oscar Peterson", "John Coltrane", "Ella Fitzgerald"],
  "Count Basie": ["Duke Ellington", "Benny Goodman", "Lionel Hampton", "Fats Waller", "Louis Armstrong", "Earl Hines", "Dizzy Gillespie", "Artie Shaw", "Roy Eldridge", "Oscar Peterson", "Art Tatum", "Coleman Hawkins"],
  "Mary Lou Williams": ["Bud Powell", "Junior Mance", "Horace Silver", "McCoy Tyner", "Ahmad Jamal", "Geri Allen", "Shirley Scott", "Andrew Hill", "Thelonious Monk", "Art Tatum", "Abdullah Ibrahim", "Joe Henderson"],
  "Nat King Cole": ["Ella Fitzgerald", "Mel Torme", "Louis Armstrong", "Sarah Vaughan", "Billie Holiday", "Anita O'Day", "Artie Shaw", "Benny Goodman", "Oscar Peterson"],
  "Bud Powell": ["Herbie Nichols", "Hank Jones", "Red Garland", "Thelonious Monk", "Charlie Parker", "Sonny Clark", "Wynton Kelly", "Barry Harris", "Dexter Gordon", "McCoy Tyner", "Hank Mobley", "Lee Morgan"],
  "Thelonious Monk": ["John Coltrane", "Bud Powell", "Miles Davis", "Charles Mingus", "Lee Morgan", "Charlie Parker", "Sonny Rollins", "Bill Evans", "Hank Mobley", "Wayne Shorter", "Cannonball Adderley", "McCoy Tyner"],
  "Al Haig": ["Bennie Green", "Cecil Payne", "Wardell Gray", "Danilo Perez"],
  "Hank Jones": ["Tommy Flanagan", "Red Garland", "Wynton Kelly", "Bud Powell", "Elmo Hope", "Barry Harris", "Mulgrew Miller", "Oscar Peterson", "Ahmad Jamal", "Herbie Nichols", "Horace Parlan", "Kenny Barron"],
  "Tommy Flanagan": ["Wynton Kelly", "Red Garland", "Hank Jones", "Sonny Clark", "Hank Mobley", "Oscar Peterson", "Bud Powell", "Barry Harris", "Bill Charlap", "Bill Evans", "McCoy Tyner", "Cedar Walton"],
  "Barry Harris": ["Elmo Hope", "Bud Powell", "Hank Jones", "Cedar Walton", "Mulgrew Miller", "Horace Parlan", "Red Garland", "Herbie Nichols", "Tommy Flanagan", "Wynton Kelly", "Jackie McLean", "Ahmad Jamal"],
  "Red Garland": ["Tommy Flanagan", "Wynton Kelly", "Hank Jones", "Bud Powell", "Sonny Clark", "Hank Mobley", "Bill Charlap", "Oscar Peterson", "McCoy Tyner", "Barry Harris", "Dexter Gordon", "Benny Golson"],
  "Wynton Kelly": ["Tommy Flanagan", "Red Garland", "Hank Jones", "Bud Powell", "Sonny Clark", "Mulgrew Miller", "McCoy Tyner", "Horace Silver", "Oscar Peterson", "Hank Mobley", "Horace Parlan", "Ahmad Jamal"],
  "Sonny Clark": ["Hank Mobley", "Lee Morgan", "Dexter Gordon", "Horace Silver", "Kenny Dorham", "Jackie McLean", "Lou Donaldson", "Freddie Hubbard", "Red Garland", "Bud Powell", "Benny Golson", "Johnny Griffin"],
  "Bill Evans": ["Cannonball Adderley", "Thelonious Monk", "Miles Davis", "McCoy Tyner", "Chet Baker", "Keith Jarrett", "Wayne Shorter", "Oscar Peterson", "Ahmad Jamal", "John Coltrane", "Red Garland", "Paul Desmond"],
  "Horace Silver": ["Hank Mobley", "Lee Morgan", "Sonny Clark", "Freddie Hubbard", "Dexter Gordon", "Jackie McLean", "Cannonball Adderley", "Art Blakey", "Stanley Turrentine", "Lou Donaldson", "Joe Henderson", "Wayne Shorter"],
  "Bobby Timmons": ["Kenny Drew", "McCoy Tyner", "Cedar Walton", "Bud Powell", "Lou Donaldson", "Sonny Clark", "Hank Mobley", "Wynton Kelly", "Lee Morgan", "Freddie Hubbard", "Tommy Flanagan", "Bill Evans"],
  "Cedar Walton": ["Mulgrew Miller", "Kenny Drew", "Barry Harris", "Junior Mance", "McCoy Tyner", "Hank Jones", "Tommy Flanagan", "Bobby Timmons", "Kenny Barron", "Bud Powell", "Joe Henderson", "Kenny Garrett"],
  "Kenny Drew": ["Cedar Walton", "Sonny Clark", "Hank Mobley", "Johnny Griffin", "Bobby Timmons", "Jackie McLean", "Lee Morgan", "Red Garland", "Wynton Kelly", "Duke Pearson", "Horace Parlan", "Kenny Dorham"],
  "Duke Pearson": ["Bobby Hutcherson", "Horace Parlan", "Lee Morgan", "Hank Mobley", "Horace Silver", "Jackie McLean", "Andrew Hill", "Kenny Dorham", "Joe Henderson", "Freddie Hubbard", "Sonny Clark", "Blue Mitchell"],
  "Horace Parlan": ["Jackie McLean", "Hank Mobley", "Lee Morgan", "Stanley Turrentine", "Dexter Gordon", "Joe Henderson", "Duke Pearson", "Elmo Hope", "Sonny Clark", "Horace Silver", "Booker Ervin", "Freddie Hubbard"],
  "Elmo Hope": ["Barry Harris", "Herbie Nichols", "Hank Jones", "Bud Powell", "Horace Parlan", "Jackie McLean", "Red Garland", "Tommy Flanagan", "Wynton Kelly", "Ahmad Jamal", "Eric Dolphy", "Lee Morgan"],
  "Herbie Nichols": ["Elmo Hope", "Bud Powell", "Hank Jones", "Barry Harris", "Horace Parlan", "Jackie McLean", "Red Garland", "Tommy Flanagan", "Andrew Hill", "Wynton Kelly", "Michel Petrucciani", "Sonny Rollins"],
  "Randy Weston": ["Andrew Hill", "McCoy Tyner", "Horace Parlan", "Bud Powell", "Horace Silver", "Mary Lou Williams", "Abdullah Ibrahim", "Mulgrew Miller", "Duke Pearson", "Keith Jarrett", "Jason Moran", "Eric Dolphy"],
  "Abdullah Ibrahim": ["Brad Mehldau", "Keith Jarrett", "Vijay Iyer", "Bud Powell", "Ahmad Jamal", "Fred Hersch", "Kenny Garrett", "Monty Alexander", "McCoy Tyner", "Charles Lloyd", "Tord Gustavsen", "Gonzalo Rubalcaba"],
  "Ahmad Jamal": ["McCoy Tyner", "Hank Jones", "Oscar Peterson", "Bill Evans", "Red Garland", "Thelonious Monk", "Freddie Hubbard", "Horace Silver", "Lee Morgan", "Wynton Kelly", "Jack DeJohnette", "Bud Powell"],
  "Oscar Peterson": ["Hank Jones", "Red Garland", "Art Tatum", "Ahmad Jamal", "Bill Evans", "Erroll Garner", "Kenny Burrell", "Tommy Flanagan", "Cannonball Adderley", "Coleman Hawkins", "Wynton Kelly", "McCoy Tyner"],
  "Erroll Garner": ["Art Tatum", "Oscar Peterson", "George Shearing", "Bud Powell", "Wynton Kelly", "Red Garland", "Hank Jones", "Earl Hines", "Ahmad Jamal", "Teddy Wilson", "McCoy Tyner", "Fats Waller"],
  "George Shearing": ["Erroll Garner", "Art Tatum", "Oscar Peterson", "Zoot Sims", "Earl Hines", "Hank Jones", "Ahmad Jamal", "Cedar Walton", "Dave Brubeck", "Bill Evans", "Teddy Wilson", "Ben Webster"],
  "Dave Brubeck": ["Oscar Peterson", "Bill Evans", "Paul Desmond", "Gerry Mulligan", "Art Blakey", "Ahmad Jamal", "Cannonball Adderley", "Horace Silver", "Vince Guaraldi", "Art Pepper", "Kenny Burrell", "Stan Getz"],
  "Vince Guaraldi": ["Dave Brubeck", "Ahmad Jamal", "Oscar Peterson", "Bill Evans", "Wynton Marsalis", "Ella Fitzgerald", "Kenny Burrell", "Duke Pearson", "Jimmy Smith", "Stan Getz", "Nat King Cole", "McCoy Tyner"],
  "Ramsey Lewis": ["Les McCann", "Charles Earland", "Jimmy McGriff", "Bobbi Humphrey", "Roy Ayers", "Joe Sample", "Herbie Hancock", "Donald Byrd", "Jimmy Smith", "Gene Harris", "Lou Donaldson", "Ahmad Jamal"],
  "Les McCann": ["Ramsey Lewis", "Jimmy Smith", "Jimmy McGriff", "Lou Donaldson", "Bobbi Humphrey", "Jackie McLean", "Charles Earland", "Roy Ayers", "Horace Silver", "Jack McDuff", "Donald Byrd", "Herbie Mann"],
  "Gene Harris": ["Donald Byrd", "Bobbi Humphrey", "Jack McDuff", "Jimmy McGriff", "Roy Ayers", "Gary Bartz", "Ramsey Lewis", "Jimmy Smith", "Lou Donaldson", "Bobby Hutcherson", "Stanley Turrentine", "Horace Silver"],
  "Junior Mance": ["Cedar Walton", "Wynton Kelly", "Ahmad Jamal", "Kenny Drew", "Bobby Timmons", "Tommy Flanagan", "Sonny Clark", "Red Garland", "Johnny Hodges", "Ramsey Lewis", "Erroll Garner", "Horace Silver"],
  "Monty Alexander": ["Ahmad Jamal", "Michel Petrucciani", "Gonzalo Rubalcaba", "Kurt Elling", "Oscar Peterson", "Kenny Barron", "Cedar Walton", "McCoy Tyner", "Hank Jones", "Christian McBride", "Tommy Flanagan", "Art Pepper"],
  "McCoy Tyner": ["Joe Henderson", "Wayne Shorter", "Lee Morgan", "Andrew Hill", "Freddie Hubbard", "John Coltrane", "Jackie McLean", "Hank Mobley", "Horace Silver", "Bud Powell", "Ahmad Jamal", "Sonny Rollins"],
  "Herbie Hancock": ["Wayne Shorter", "Miles Davis", "Chick Corea", "Freddie Hubbard", "Lee Morgan", "Joe Henderson", "Cannonball Adderley", "McCoy Tyner", "Sonny Rollins", "John Coltrane", "Thelonious Monk", "Charles Mingus"],
  "Chick Corea": ["Herbie Hancock", "Gary Burton", "Keith Jarrett", "Wayne Shorter", "Brad Mehldau", "Pat Metheny", "Miles Davis", "McCoy Tyner", "Freddie Hubbard", "Christian McBride", "Joshua Redman", "Michael Brecker"],
  "Keith Jarrett": ["Brad Mehldau", "Fred Hersch", "Paul Bley", "Gary Peacock", "Bill Evans", "Chick Corea", "Ralph Towner", "Charlie Haden", "Jack DeJohnette", "Charles Lloyd", "Paul Motian", "Bobo Stenson"],
  "Paul Bley": ["Paul Motian", "Keith Jarrett", "Jimmy Giuffre", "Gary Peacock", "Charlie Haden", "Ralph Towner", "Bill Evans", "Ornette Coleman", "Dave Holland", "Cecil Taylor", "Andrew Hill", "Fred Hersch"],
  "Andrew Hill": ["Jackie McLean", "Eric Dolphy", "Bobby Hutcherson", "Grachan Moncur III", "Cecil Taylor", "Joe Henderson", "McCoy Tyner", "Larry Young", "Wayne Shorter", "Booker Ervin", "Ornette Coleman", "Archie Shepp"],
  "Cecil Taylor": ["Albert Ayler", "Ornette Coleman", "Andrew Hill", "Eric Dolphy", "Marion Brown", "Don Cherry", "Archie Shepp", "Grachan Moncur III", "Jimmy Giuffre", "Dave Holland", "John Coltrane", "Jackie McLean"],
  "Don Pullen": ["Muhal Richard Abrams", "Dewey Redman", "Greg Osby", "Tim Berne", "Hamiet Bluiett", "Sunny Murray", "Danilo Perez", "Andrew Cyrille", "Billy Bang", "Walt Dickerson", "Cecil McBee", "Steve Coleman"],
  "Muhal Richard Abrams": ["Tim Berne", "Dewey Redman", "Sunny Murray", "Don Pullen", "Milford Graves", "Hamiet Bluiett", "Billy Bang", "Andrew Cyrille", "Greg Osby", "Steve Coleman", "Roswell Rudd", "Rudresh Mahanthappa"],
  "Joe Zawinul": ["Jaco Pastorius", "John McLaughlin", "Chick Corea", "Tony Williams", "Herbie Hancock", "Wayne Shorter", "Pat Metheny", "Miles Davis", "Miroslav Vitous", "John Scofield", "Freddie Hubbard", "Stanley Clarke"],
  "Joe Sample": ["David Sanborn", "George Benson", "Marcus Miller", "Pat Metheny", "Stanley Clarke", "Ramsey Lewis"],
  "Kenny Barron": ["Mulgrew Miller", "Hank Jones", "Oscar Peterson", "Cedar Walton", "Aaron Parks", "Charles Lloyd", "Ahmad Jamal", "Fred Hersch", "Red Garland", "Tommy Flanagan", "McCoy Tyner", "Michel Petrucciani"],
  "Mulgrew Miller": ["Cedar Walton", "Geri Allen", "Kenny Barron", "Hank Jones", "Barry Harris", "Wynton Kelly", "McCoy Tyner", "Jason Moran", "Benny Green", "Red Garland", "Tommy Flanagan", "Ahmad Jamal"],
  "James Williams": ["Tommy Flanagan", "George Coleman"],
  "Geri Allen": ["Mulgrew Miller", "Jason Moran", "Bud Powell", "Joey DeFrancesco", "Aaron Parks", "Wynton Kelly", "Craig Taborn", "Kenny Barron", "Andrew Hill", "Thelonious Monk", "Cecil Taylor", "Vijay Iyer"],
  "Marcus Roberts": ["Michel Petrucciani", "Oscar Peterson", "Tommy Flanagan", "Ahmad Jamal", "Wynton Marsalis", "Bill Charlap", "Hank Jones", "Kenny Barron", "George Shearing", "Keith Jarrett", "Barry Harris", "McCoy Tyner"],
  "Michel Petrucciani": ["Marcus Miller", "Keith Jarrett", "Gonzalo Rubalcaba", "Brad Mehldau", "Oscar Peterson", "Kenny Barron", "Chick Corea", "Ahmad Jamal", "Avishai Cohen", "Monty Alexander", "Bill Evans", "Fred Hersch"],
  "Martial Solal": ["Erroll Garner", "Oscar Peterson", "Ahmad Jamal", "Bud Powell", "Michel Petrucciani", "Hank Jones", "Red Garland", "Geri Allen", "Kenny Barron", "McCoy Tyner", "Sonny Clark", "Keith Jarrett"],
  "Bobo Stenson": ["Tord Gustavsen", "John Abercrombie", "Peter Erskine", "Enrico Rava", "Keith Jarrett", "Gary Peacock", "Joe Lovano", "Charles Lloyd", "Gonzalo Rubalcaba", "Kenny Wheeler", "Vijay Iyer", "Paul Motian"],
  "Esbjorn Svensson": ["Avishai Cohen", "Brad Mehldau", "Aaron Parks", "Tord Gustavsen", "Michel Petrucciani", "Keith Jarrett", "Bobo Stenson", "Joshua Redman", "Vijay Iyer", "Charles Lloyd", "Joe Lovano"],
  "Tord Gustavsen": ["Bobo Stenson", "Gonzalo Rubalcaba", "Charles Lloyd", "Enrico Rava", "Charlie Haden", "Vijay Iyer", "Keith Jarrett", "Joe Lovano", "Kenny Barron", "Fred Hersch", "Gary Peacock", "Avishai Cohen"],
  "Gonzalo Rubalcaba": ["Charlie Haden", "Tord Gustavsen", "Bobo Stenson", "Brad Mehldau", "Michel Petrucciani", "Kenny Barron", "Charles Lloyd", "Keith Jarrett", "Monty Alexander", "Christian McBride", "Bill Evans", "Chucho Valdes"],
  "Danilo Perez": ["Greg Osby", "Joe Locke", "Don Pullen", "Randy Brecker", "Muhal Richard Abrams", "Dave Liebman"],
  "Chucho Valdes": ["Arturo Sandoval", "Gonzalo Rubalcaba", "Eddie Palmieri", "Fred Hersch", "Chick Corea", "Brad Mehldau", "Milt Jackson", "Cal Tjader", "Kenny Barron", "Michel Petrucciani", "Ralph Towner", "Bud Powell"],
  "Eddie Palmieri": ["Cal Tjader"],
  "Fred Hersch": ["Keith Jarrett", "Brad Mehldau", "Ralph Towner", "Joshua Redman", "Enrico Rava", "Aaron Parks", "Kenny Barron", "Vijay Iyer", "Charles Lloyd", "Jason Moran", "Joe Lovano", "Tord Gustavsen"],
  "Bill Charlap": ["Red Garland", "Tommy Flanagan", "Benny Green", "Wynton Kelly", "Hank Jones", "Keith Jarrett", "Sonny Clark", "Geri Allen", "Oscar Peterson", "McCoy Tyner", "Ahmad Jamal", "Brad Mehldau"],
  "Benny Green": ["Mulgrew Miller", "Bill Charlap", "Ethan Iverson", "Wynton Kelly", "Walter Smith III", "Oscar Peterson", "Roy Hargrove", "Cedar Walton", "Duke Pearson", "McCoy Tyner", "Hank Jones", "Fred Hersch"],
  "Brad Mehldau": ["Keith Jarrett", "Fred Hersch", "Joshua Redman", "Chick Corea", "Aaron Parks", "Charles Lloyd", "Avishai Cohen", "Jason Moran", "Walter Smith III", "Gonzalo Rubalcaba", "Julian Lage", "Bill Evans"],
  "Jason Moran": ["Vijay Iyer", "Geri Allen", "Dave Douglas", "Ambrose Akinmusire", "Brad Mehldau", "Mulgrew Miller", "Aaron Parks", "Charles Lloyd", "Gerald Clayton", "Mark Turner", "Walter Smith III", "Fred Hersch"],
  "Vijay Iyer": ["Jason Moran", "Ambrose Akinmusire", "Dave Douglas", "Mark Turner", "Joe Lovano", "Aaron Parks", "Craig Taborn", "Bobo Stenson", "Linda May Han Oh", "Tord Gustavsen", "Brad Mehldau", "Dave Holland"],
  "Robert Glasper": ["Brad Mehldau", "Aaron Parks", "Roy Hargrove", "Kenny Garrett", "Nubya Garcia", "Joshua Redman", "Melissa Aldana", "Kurt Elling", "Fred Hersch", "Marquis Hill", "Vijay Iyer", "Ahmad Jamal"],
  "Craig Taborn": ["Ralph Towner", "Mark Turner", "Vijay Iyer", "Kris Davis", "Dave Holland", "Dave Douglas", "Geri Allen", "Paul Motian", "Charles Lloyd", "Chris Potter", "Aaron Parks", "Jason Moran"],
  "Ethan Iverson": ["Benny Green", "Aaron Parks", "Walter Smith III", "Dave Douglas", "Mark Turner", "Jason Moran", "Craig Taborn", "Fred Hersch", "Cedar Walton", "Brad Mehldau", "Vijay Iyer", "Keith Jarrett"],
  "Hiromi": ["Chick Corea", "Michel Petrucciani", "Brad Mehldau", "Keith Jarrett", "Avishai Cohen", "Aaron Parks", "Robert Glasper", "Ahmad Jamal", "Bill Evans", "Oscar Peterson", "Marcus Miller", "Kamasi Washington"],
  "Aaron Parks": ["Brad Mehldau", "Avishai Cohen", "Kurt Rosenwinkel", "Immanuel Wilkins", "Vijay Iyer", "Kenny Barron", "Fred Hersch", "Joshua Redman", "Gerald Clayton", "Julian Lage", "Walter Smith III", "Melissa Aldana"],
  "Kris Davis": ["Dave Douglas", "Craig Taborn", "Mary Halvorson", "Ambrose Akinmusire", "Bill Frisell", "Andrew Hill", "Immanuel Wilkins", "Walter Smith III", "Ralph Towner", "Julian Lage", "Mark Turner", "Dave Holland"],
  "Sullivan Fortner": ["Gerald Clayton", "Melissa Aldana", "Immanuel Wilkins", "Cecile McLorin Salvant", "Brad Mehldau", "Al Foster", "Ambrose Akinmusire", "Branford Marsalis", "Walter Smith III", "Julian Lage", "Charles Lloyd", "John Patitucci"],
  "Jon Batiste": ["Gregory Porter", "Brad Mehldau", "Cecile McLorin Salvant", "Julian Lage", "Robert Glasper", "Keith Jarrett", "Avishai Cohen", "Cory Henry", "Joey Alexander", "Christian McBride", "Oscar Peterson", "Joshua Redman"],
  "Gerald Clayton": ["Ambrose Akinmusire", "Sullivan Fortner", "Immanuel Wilkins", "Gilad Hekselman", "Aaron Parks", "Walter Smith III", "Jason Moran", "Charles Lloyd", "Joshua Redman", "Brad Mehldau", "Branford Marsalis", "Melissa Aldana"],
  "Joey Alexander": ["Avishai Cohen", "Lakecia Benjamin", "Terri Lyne Carrington", "Ahmad Jamal", "Brad Mehldau", "Joshua Redman", "Charles Lloyd", "Sullivan Fortner", "Kenny Barron", "Hiromi", "Michel Petrucciani", "Aaron Parks"],
  "Milt Hinton": ["Leroy Vinnegar", "Scott LaFaro", "Slam Stewart", "Red Mitchell", "Rufus Reid", "Sam Jones", "Eddie Gomez", "Ray Drummond"],
  "Slam Stewart": ["Barney Bigard", "Edmond Hall", "Pee Wee Russell", "Milt Hinton", "Rex Stewart", "Cootie Williams", "Buck Clayton"],
  "Oscar Pettiford": ["Paul Chambers", "Bud Powell", "Sonny Stitt", "Sonny Criss", "Dizzy Gillespie", "Horace Silver", "Lee Morgan", "Thelonious Monk", "Hank Mobley", "Freddie Hubbard", "Charles Mingus", "Charlie Parker"],
  "Ray Brown": ["Oscar Peterson", "Cannonball Adderley", "Christian McBride", "Sonny Stitt", "Ron Carter", "Paul Chambers", "Kenny Burrell", "Lee Morgan", "Milt Jackson", "Charlie Haden", "Bud Powell", "Hank Jones"],
  "Percy Heath": ["Kenny Clarke", "Scott LaFaro", "Ruby Braff", "Leroy Vinnegar", "Conte Candoli", "Rufus Reid", "Red Mitchell", "Ray Brown", "Paul Chambers", "Herb Geller", "Doug Watkins", "Sam Jones"],
  "Wilbur Ware": ["Doug Watkins", "Pepper Adams", "Elmo Hope", "Jackie McLean", "Max Roach", "Clifford Jordan", "Paul Chambers", "Red Mitchell", "Elvin Jones", "Wayne Shorter", "Sam Jones", "Don Patterson"],
  "Paul Chambers": ["Lee Morgan", "Cannonball Adderley", "Hank Mobley", "Dexter Gordon", "Sonny Clark", "Kenny Burrell", "Sonny Rollins", "Ron Carter", "Joe Henderson", "Johnny Griffin", "Jackie McLean", "Freddie Hubbard"],
  "Doug Watkins": ["Red Mitchell", "Leroy Vinnegar", "Pepper Adams", "Wilbur Ware", "Frank Foster", "Scott LaFaro", "Arnett Cobb", "Sam Jones", "Reggie Workman", "Cecil Payne", "Cecil McBee", "Frank Wess"],
  "Sam Jones": ["Leroy Vinnegar", "Red Mitchell", "Scott LaFaro", "Milt Hinton", "Rufus Reid", "Pepper Adams", "Cecil Payne", "Eddie Gomez", "Doug Watkins", "Bennie Green", "Arnett Cobb", "George Coleman"],
  "Leroy Vinnegar": ["Red Mitchell", "Milt Hinton", "Scott LaFaro", "Conte Candoli", "Sam Jones", "Slam Stewart", "Cecil McBee", "Rufus Reid", "Mel Lewis", "Doug Watkins", "Frank Rosolino", "Cecil Payne"],
  "Red Mitchell": ["Rufus Reid", "Leroy Vinnegar", "Carl Fontana", "Milt Hinton", "Scott LaFaro", "Cecil Payne", "Eddie Gomez", "Frank Wess", "Sam Jones", "Doug Watkins", "Mel Lewis", "Ray Drummond"],
  "Charles Mingus": ["John Coltrane", "Miles Davis", "Thelonious Monk", "Eric Dolphy", "Wayne Shorter", "Ornette Coleman", "Cannonball Adderley", "Sonny Rollins", "McCoy Tyner", "Lee Morgan", "Dexter Gordon", "Herbie Hancock"],
  "Scott LaFaro": ["Milt Hinton", "Leroy Vinnegar", "Red Mitchell", "Rufus Reid", "Eddie Gomez", "Slam Stewart", "Sam Jones", "Doug Watkins", "Ray Drummond", "Ravi Coltrane", "Percy Heath", "Ray Brown"],
  "Gary Peacock": ["John Abercrombie", "Charlie Haden", "Keith Jarrett", "Ralph Towner", "Dave Holland", "Bobo Stenson", "Enrico Rava", "Charles Lloyd", "Paul Motian", "Peter Erskine", "Christian McBride", "Paul Bley"],
  "Charlie Haden": ["Gary Peacock", "Dave Holland", "Keith Jarrett", "Gonzalo Rubalcaba", "Christian McBride", "Pat Metheny", "Joe Lovano", "Ralph Towner", "Bill Frisell", "John Scofield", "Charles Lloyd", "John Abercrombie"],
  "Jimmy Garrison": ["Charlie Haden", "Paul Chambers", "Ray Brown", "Milt Hinton", "Leroy Vinnegar", "Scott LaFaro", "Cecil McBee"],
  "Reggie Workman": ["Andrew Cyrille", "Muhal Richard Abrams", "Tim Berne", "Cecil McBee", "Dewey Redman", "Walt Dickerson", "Sunny Murray", "Roswell Rudd", "Don Pullen", "Doug Watkins", "Andrew Hill", "Dave Liebman"],
  "Ron Carter": ["Paul Chambers", "Christian McBride", "Herbie Hancock", "Stanley Turrentine", "Art Pepper", "Freddie Hubbard", "Hank Mobley", "Charlie Haden", "Lou Donaldson", "Cedar Walton", "Gary Peacock", "Blue Mitchell"],
  "Cecil McBee": ["Muhal Richard Abrams", "Hamiet Bluiett", "Leroy Vinnegar", "Walt Dickerson", "Dewey Redman", "Don Pullen", "Cecil Payne", "Sunny Murray", "Andrew Cyrille"],
  "Buster Williams": ["Ron Carter", "Joe Lovano", "Avishai Cohen", "Keith Jarrett", "Gonzalo Rubalcaba", "Gary Burton", "Steve Swallow", "Fred Hersch", "Michel Petrucciani", "Christian McBride", "Kenny Barron", "Clark Terry"],
  "Eddie Gomez": ["Rufus Reid", "Red Mitchell", "Scott LaFaro", "Danilo Perez", "Randy Brecker", "Leroy Vinnegar", "Milt Hinton"],
  "Miroslav Vitous": ["Steve Swallow", "Joe Lovano", "Mark Turner", "Dave Holland", "John Abercrombie", "Gary Peacock", "Jack DeJohnette", "Peter Erskine", "Ralph Towner", "Larry Coryell", "Enrico Rava", "Bill Frisell"],
  "Dave Holland": ["John Abercrombie", "Charlie Haden", "Gary Peacock", "Kenny Wheeler", "Andrew Hill", "Charles Lloyd", "Miroslav Vitous", "Keith Jarrett", "Chris Potter", "Bill Frisell", "Cecil Taylor", "Paul Motian"],
  "Niels-Henning Orsted Pedersen": ["Scott LaFaro", "Sam Jones", "Red Mitchell", "Eddie Gomez", "Milt Hinton", "Leroy Vinnegar", "Rufus Reid"],
  "Rufus Reid": ["Red Mitchell", "Eddie Gomez", "Scott LaFaro", "Milt Hinton", "Leroy Vinnegar", "Joe Locke", "Carl Fontana", "Cecil Payne", "Ray Drummond", "Frank Rosolino"],
  "Ray Drummond": ["Jimmy Cobb", "Harry Edison", "Joe Locke", "Rufus Reid", "Red Mitchell", "Leroy Vinnegar"],
  "Steve Swallow": ["Miroslav Vitous", "Kenny Wheeler", "Gary Peacock", "Paul Motian", "Joe Lovano", "Charlie Haden", "Dave Holland", "Gary Burton", "Mark Turner", "John Scofield", "Charles Lloyd", "Keith Jarrett"],
  "Jaco Pastorius": ["Stanley Clarke", "Marcus Miller", "Chick Corea", "Herbie Hancock", "Pat Metheny", "John McLaughlin", "Jean-Luc Ponty", "Al Di Meola", "John Scofield", "Miles Davis", "Wayne Shorter", "Tony Williams"],
  "Stanley Clarke": ["Marcus Miller", "John Scofield", "Jaco Pastorius", "Jean-Luc Ponty", "Al Di Meola", "Tony Williams", "Joe Sample", "John McLaughlin", "Chick Corea", "Larry Coryell", "Mike Stern", "Herbie Hancock"],
  "Marcus Miller": ["Stanley Clarke", "Christian McBride", "Michel Petrucciani", "David Sanborn", "Joe Sample", "John Scofield", "Jaco Pastorius", "Mike Stern", "John Patitucci", "Herbie Hancock", "Pat Metheny", "Gregory Porter"],
  "Christian McBride": ["Joshua Redman", "Marcus Miller", "Charlie Haden", "Charles Lloyd", "Ron Carter", "Chris Potter", "Chick Corea", "Gregory Porter", "Gary Peacock", "Ray Brown", "Kenny Burrell", "Brad Mehldau"],
  "John Patitucci": ["Michael Brecker", "Peter Erskine", "Marcus Miller", "Pat Metheny", "Christian McBride", "Stanley Clarke", "John Scofield", "Dave Holland", "Gerald Clayton", "Vijay Iyer", "Chick Corea", "Ambrose Akinmusire"],
  "Larry Grenadier": ["Immanuel Wilkins", "Aaron Parks", "Charlie Haden", "Gary Peacock", "Christian McBride", "Keith Jarrett", "Charles Lloyd", "Bill Frisell", "Julian Lage", "Pat Metheny", "Brad Mehldau", "John Patitucci"],
  "Avishai Cohen (bass)": ["Stefon Harris", "Danilo Perez", "Avishai Cohen", "Greg Osby", "Rudresh Mahanthappa", "Billy Hart", "Jeff Tain Watts", "Joe Locke"],
  "Esperanza Spalding": ["Cecile McLorin Salvant", "Roy Hargrove", "Robert Glasper", "Kamasi Washington", "Brad Mehldau", "Jaco Pastorius", "Wayne Shorter", "Herbie Hancock", "Joshua Redman", "Chick Corea", "Gregory Porter", "Nubya Garcia"],
  "Linda May Han Oh": ["Dave Douglas", "Mark Turner", "Vijay Iyer", "Mary Halvorson", "Charles Lloyd", "Cecile McLorin Salvant", "Immanuel Wilkins", "Joshua Redman", "Ambrose Akinmusire", "Lakecia Benjamin", "Terri Lyne Carrington", "Fred Hersch"],
  "Ben Williams": ["Marquis Hill", "Gerald Clayton", "Ambrose Akinmusire", "Aaron Parks", "Christian McBride", "Robert Glasper", "Makaya McCraven", "Jason Moran", "Esperanza Spalding", "Roy Hargrove", "Brad Mehldau", "Immanuel Wilkins"],
  "Matt Brewer": ["Eric Harland", "Bill Stewart", "Greg Osby", "Dave Liebman"],
  "Baby Dodds": ["Sid Catlett", "Jo Jones", "Eric Harland", "Billy Higgins", "Bill Stewart", "Johnny Dodds", "Kenny Clarke", "Billy Hart", "Edmond Hall", "Milford Graves", "Pee Wee Russell", "Mel Lewis"],
  "Chick Webb": ["Count Basie", "Artie Shaw", "Tommy Dorsey", "Lionel Hampton", "Gene Krupa", "Fats Waller", "Benny Goodman", "Duke Ellington", "Jack Teagarden", "Ella Fitzgerald", "Illinois Jacquet", "Earl Hines"],
  "Gene Krupa": ["Benny Goodman", "Tommy Dorsey", "Buddy Rich", "Artie Shaw", "Chick Webb", "Count Basie", "Duke Ellington", "Anita O'Day", "Lionel Hampton", "Lester Young", "Johnny Hodges", "Jack Teagarden"],
  "Jo Jones": ["Jimmy Cobb", "Harry Edison", "Kenny Clarke", "Paul Gonsalves", "Pee Wee Russell", "Buck Clayton", "Jeff Tain Watts", "Cootie Williams", "Rex Stewart", "Vic Dickenson", "Baby Dodds", "Sid Catlett"],
  "Sid Catlett": ["Harry Carney", "Baby Dodds", "Edmond Hall", "Cootie Williams", "Buck Clayton", "Wardell Gray", "Jo Jones", "Kenny Clarke", "Barney Bigard", "Jimmie Noone", "Pee Wee Russell", "Rex Stewart"],
  "Buddy Rich": ["Maynard Ferguson", "Count Basie", "Gene Krupa", "Dizzy Gillespie", "Benny Goodman", "Art Blakey", "Charlie Parker", "Duke Ellington", "Lester Young", "Freddie Hubbard", "Max Roach", "Coleman Hawkins"],
  "Kenny Clarke": ["Bennie Green", "Wardell Gray", "Jo Jones", "Cecil Payne", "Frank Wess", "Jimmy Cobb", "Arnett Cobb", "Al Haig", "Frank Rosolino", "Percy Heath", "Conte Candoli", "Terry Gibbs"],
  "Max Roach": ["Eric Dolphy", "Jackie McLean", "Andrew Hill", "Charles Mingus", "Wayne Shorter", "Ornette Coleman", "Lee Morgan", "Freddie Hubbard", "Joe Henderson", "McCoy Tyner", "Art Blakey", "Sonny Rollins"],
  "Art Blakey": ["Lee Morgan", "Hank Mobley", "Horace Silver", "Wayne Shorter", "Freddie Hubbard", "Dexter Gordon", "Kenny Dorham", "Cannonball Adderley", "Jackie McLean", "Sonny Clark", "Joe Henderson", "Clifford Brown"],
  "Philly Joe Jones": ["Elvin Jones", "Roy Haynes", "Max Roach", "Jackie McLean", "Hank Mobley", "Paul Chambers", "Art Blakey", "Freddie Hubbard", "Lee Morgan", "Sonny Clark", "Horace Silver", "Cannonball Adderley"],
  "Roy Haynes": ["Philly Joe Jones", "Jackie McLean", "Max Roach", "Elvin Jones", "Johnny Griffin", "Hank Mobley", "Freddie Hubbard", "Horace Parlan", "Blue Mitchell", "Lee Morgan", "Wayne Shorter", "Booker Ervin"],
  "Shelly Manne": ["Zoot Sims", "Bud Shank", "Curtis Fuller", "Jackie McLean", "Gerry Mulligan", "Harold Land", "Art Pepper", "Art Farmer", "Cannonball Adderley", "Kenny Dorham", "Blue Mitchell", "Lee Morgan"],
  "Chico Hamilton": ["Stanley Turrentine", "Lee Konitz", "Andrew Hill", "Donald Byrd", "Bobby Hutcherson", "Max Roach", "Eric Dolphy", "Joe Henderson", "Gene Harris", "Jack McDuff", "Elvin Jones", "Duke Pearson"],
  "Connie Kay": ["Frank Rosolino", "Carl Fontana", "Frank Wess", "Mel Lewis", "Marcus Gilmore", "Seamus Blake", "Bobby Hackett", "Bob Berg", "Arnett Cobb"],
  "Jimmy Cobb": ["Harry Edison", "Ray Drummond", "Von Freeman", "Jeff Tain Watts", "Vincent Herring", "Joe Locke", "Jo Jones", "George Coleman"],
  "Louis Hayes": ["Milt Jackson", "Monty Alexander", "Gene Ammons", "Blue Mitchell", "Art Pepper", "Benny Golson", "Dexter Gordon", "Kenny Dorham", "Jackie McLean", "Ron Carter", "Cannonball Adderley", "Stanley Turrentine"],
  "Pete La Roca": ["Joe Henderson", "Bobby Hutcherson", "Jackie McLean", "Lee Morgan", "Booker Ervin", "Wayne Shorter", "McCoy Tyner", "Freddie Hubbard", "Yusef Lateef", "Woody Shaw", "Duke Pearson", "Stanley Turrentine"],
  "Elvin Jones": ["Jackie McLean", "Booker Ervin", "Joe Henderson", "Wayne Shorter", "Andrew Hill", "Lee Morgan", "Bobby Hutcherson", "Hank Mobley", "Woody Shaw", "Archie Shepp", "John Coltrane", "Larry Young"],
  "Tony Williams": ["Elvin Jones", "John McLaughlin", "Andrew Hill", "Stanley Clarke", "Miles Davis", "Wayne Shorter", "Jean-Luc Ponty", "Jackie McLean", "Freddie Hubbard", "Herbie Hancock", "Joe Zawinul", "Archie Shepp"],
  "Joe Chambers": ["Elvin Jones", "Max Roach", "Jackie McLean", "McCoy Tyner", "Larry Young", "Clifford Jordan", "Andrew Hill", "Woody Shaw", "Blue Mitchell", "Wayne Shorter", "Donald Byrd", "Jack DeJohnette"],
  "Billy Higgins": ["Bob Berg", "Bill Stewart", "Jeff Tain Watts", "Walt Dickerson", "Ravi Coltrane", "Billy Hart", "Eric Harland", "Frank Wess", "Kenny Clarke", "Don Pullen", "Steve Coleman", "George Coleman"],
  "Ed Blackwell": ["Andrew Cyrille", "Rashied Ali", "Muhal Richard Abrams", "Dewey Redman", "Milford Graves", "Han Bennink", "Sunny Murray", "Tim Berne", "Don Pullen", "Hamiet Bluiett", "Billy Hart", "Billy Higgins"],
  "Paul Motian": ["Bill Frisell", "Paul Bley", "John Abercrombie", "Kenny Wheeler", "Charles Lloyd", "Keith Jarrett", "Ralph Towner", "Dave Holland", "Gary Peacock", "Mark Turner", "Joe Lovano", "Jack DeJohnette"],
  "Ben Riley": ["Jimmy Cobb", "Eric Harland", "Bill Stewart", "Billy Hart", "Jeff Tain Watts", "Andrew Cyrille", "Rufus Reid", "Wardell Gray"],
  "Mel Lewis": ["Frank Rosolino", "Carl Fontana", "Jeff Tain Watts", "Leroy Vinnegar", "Vincent Herring", "Wycliffe Gordon", "Eric Harland", "Ingrid Jensen", "Lage Lund", "Herb Geller"],
  "Jack DeJohnette": ["Ralph Towner", "John Abercrombie", "Keith Jarrett", "John Scofield", "Ahmad Jamal", "Paul Motian", "Charles Lloyd", "Bill Frisell", "Miroslav Vitous", "Dave Holland", "Kenny Wheeler", "Gary Burton"],
  "Al Foster": ["Sullivan Fortner", "Melissa Aldana", "John Scofield", "Kenny Barron", "Cedar Walton", "Joshua Redman", "Aaron Parks", "Walter Smith III", "Peter Bernstein", "Pat Metheny", "Chick Corea", "Charles Lloyd"],
  "Billy Hart": ["Bill Stewart", "Andrew Cyrille", "Eric Harland", "Jeff Tain Watts", "Tim Berne", "Greg Osby", "Rudresh Mahanthappa"],
  "Andrew Cyrille": ["Sunny Murray", "Muhal Richard Abrams", "Dewey Redman", "Tim Berne", "Walt Dickerson", "Billy Bang", "Milford Graves", "Billy Hart", "Don Pullen", "Rashied Ali", "Hamiet Bluiett"],
  "Sunny Murray": ["Milford Graves", "Dewey Redman", "Muhal Richard Abrams", "Rashied Ali", "Tim Berne", "Andrew Cyrille", "Han Bennink", "Billy Bang"],
  "Rashied Ali": ["Milford Graves", "Sunny Murray", "Dewey Redman", "Andrew Cyrille", "Muhal Richard Abrams", "Han Bennink", "Tim Berne", "Cecil McBee", "Ed Blackwell", "Billy Bang", "Don Pullen"],
  "Milford Graves": ["Sunny Murray", "Rashied Ali", "Tim Berne", "Dewey Redman", "Han Bennink", "Muhal Richard Abrams"],
  "Han Bennink": ["Milford Graves", "Sunny Murray", "Rashied Ali", "Andrew Cyrille", "Tim Berne"],
  "Peter Erskine": ["John Abercrombie", "Bobo Stenson", "Gary Peacock", "Ralph Towner", "Kenny Wheeler", "Enrico Rava", "Paul Motian", "Avishai Cohen", "John Patitucci", "Charles Lloyd", "Miroslav Vitous", "Jack DeJohnette"],
  "Steve Gadd": ["Randy Brecker", "Bob Berg", "Jeff Tain Watts", "Jimmy Cobb"],
  "Jeff Tain Watts": ["Greg Osby", "Bill Stewart", "Stefon Harris", "Eric Harland", "Bob Berg", "Ravi Coltrane", "Jimmy Cobb", "Billy Hart", "Joe Locke", "Steve Coleman", "Dave Liebman", "Rudresh Mahanthappa"],
  "Brian Blade": ["Walter Smith III", "Paul Motian", "Kurt Rosenwinkel", "Mark Turner", "Joshua Redman", "Immanuel Wilkins", "Cecile McLorin Salvant", "Pat Martino", "Ambrose Akinmusire", "Chris Potter", "Aaron Parks", "Kenny Garrett"],
  "Bill Stewart": ["Jeff Tain Watts", "Eric Harland", "Lage Lund", "Seamus Blake", "Billy Hart", "Stefon Harris", "Matt Brewer", "Greg Osby", "Dave Liebman", "Vincent Herring"],
  "Antonio Sanchez": ["Bill Stewart", "Eric Harland", "Steve Gadd", "Billy Hart", "Andrew Cyrille", "Jo Jones", "Rudresh Mahanthappa", "Jeff Tain Watts"],
  "Terri Lyne Carrington": ["Lakecia Benjamin", "Cecile McLorin Salvant", "Linda May Han Oh", "Charles Lloyd", "Nate Smith", "Joey Alexander", "Jason Moran", "Chris Potter", "Miroslav Vitous", "Joshua Redman", "Peter Erskine", "Joe Lovano"],
  "Cindy Blackman Santana": ["Sullivan Fortner", "Cecile McLorin Salvant"],
  "Eric Harland": ["Bill Stewart", "Jeff Tain Watts", "Lage Lund", "Seamus Blake", "Billy Hart", "Rudresh Mahanthappa", "Steve Lehman", "Matt Brewer", "Stefon Harris", "Ravi Coltrane", "Greg Osby", "Danilo Perez"],
  "Marcus Gilmore": ["Bob Berg", "Seamus Blake", "Ravi Coltrane"],
  "Nate Smith": ["Terri Lyne Carrington"],
  "Makaya McCraven": ["Nubya Garcia", "Mary Halvorson", "Ambrose Akinmusire", "Marquis Hill", "Gerald Clayton", "Linda May Han Oh", "Charles Lloyd", "Immanuel Wilkins", "Julian Lage", "Dave Douglas"],
  "Eddie Lang": ["Stuff Smith", "Pee Wee Russell", "Mark Whitfield"],
  "Django Reinhardt": ["Stephane Grappelli", "Charlie Christian", "Sidney Bechet", "Benny Goodman", "Joe Pass", "Fats Waller", "Wes Montgomery", "Louis Armstrong", "Duke Ellington", "Count Basie", "Coleman Hawkins", "Art Tatum"],
  "Charlie Christian": ["Tal Farlow", "Barney Kessel", "Herb Ellis", "Grant Green", "Django Reinhardt", "Jim Hall", "Joe Pass", "Pat Martino", "Wes Montgomery", "Benny Goodman", "Kenny Burrell", "Jimmy Raney"],
  "Oscar Moore": ["Eddie Lang", "Wardell Gray", "Leroy Vinnegar", "Mark Whitfield", "Herb Geller", "Tiny Grimes", "Terry Gibbs", "Al Cohn", "Frank Rosolino", "Mel Lewis"],
  "Freddie Green": ["Eddie Lang", "Frank Wess", "Tiny Grimes", "Lage Lund"],
  "Barney Kessel": ["Tal Farlow", "Herb Ellis", "Kenny Burrell", "Joe Pass", "Charlie Christian", "Russell Malone", "Jimmy Raney", "Jim Hall", "Pat Martino", "Grant Green", "Wes Montgomery", "Gerry Mulligan"],
  "Tal Farlow": ["Pat Martino", "Joe Pass", "Wes Montgomery", "Jim Hall", "Barney Kessel", "Herb Ellis", "Charlie Christian", "Jimmy Raney", "Kenny Burrell", "Sonny Criss", "Grant Green", "Emily Remler"],
  "Jimmy Raney": ["Tal Farlow", "Pat Martino", "Joe Pass", "Wes Montgomery", "Barney Kessel", "Shorty Rogers", "Houston Person", "Kenny Burrell", "Jim Hall", "Herb Ellis", "Lee Konitz", "Grant Green"],
  "Herb Ellis": ["Tal Farlow", "Barney Kessel", "Joe Pass", "Charlie Christian", "Jim Hall", "Pat Martino", "Wes Montgomery", "Kenny Burrell", "Jimmy Raney", "Grant Green", "Russell Malone", "Oscar Peterson"],
  "Kenny Burrell": ["Grant Green", "Wes Montgomery", "Cannonball Adderley", "Lee Morgan", "Dexter Gordon", "Barney Kessel", "Tal Farlow", "Sonny Rollins", "Hank Mobley", "Art Pepper", "Jim Hall", "Stanley Turrentine"],
  "Wes Montgomery": ["Grant Green", "Pat Martino", "Kenny Burrell", "Joe Pass", "Tal Farlow", "Jim Hall", "Jimmy Smith", "Emily Remler", "Stanley Turrentine", "Barney Kessel", "Lee Morgan", "Cannonball Adderley"],
  "Grant Green": ["Kenny Burrell", "Wes Montgomery", "Pat Martino", "Lee Morgan", "Hank Mobley", "Lou Donaldson", "Joe Pass", "Jim Hall", "Dexter Gordon", "Stanley Turrentine", "Freddie Hubbard", "Tal Farlow"],
  "Jim Hall": ["Joe Pass", "Pat Martino", "Tal Farlow", "Wes Montgomery", "Kenny Burrell", "Grant Green", "Paul Desmond", "Herb Ellis", "Barney Kessel", "Bill Evans", "Kurt Rosenwinkel", "Art Farmer"],
  "Joe Pass": ["Wes Montgomery", "Tal Farlow", "Pat Martino", "Jim Hall", "Barney Kessel", "Grant Green", "Herb Ellis", "Kenny Burrell", "John Scofield", "Charlie Christian", "Emily Remler", "Kurt Rosenwinkel"],
  "George Benson": ["Joe Sample", "David Sanborn", "Wes Montgomery", "Grant Green", "Pat Martino", "Gregory Porter", "Pat Metheny", "Kenny Burrell", "Bobbi Humphrey", "Herbie Hancock", "Ramsey Lewis", "Roy Ayers"],
  "Pat Martino": ["Tal Farlow", "Wes Montgomery", "Joe Pass", "Jim Hall", "Grant Green", "Emily Remler", "Kenny Burrell", "Kurt Rosenwinkel", "Jimmy Raney", "John Scofield", "Herb Ellis", "Larry Coryell"],
  "Larry Coryell": ["John McLaughlin", "Pat Martino", "Al Di Meola", "Gary Burton", "John Abercrombie", "John Scofield", "Stanley Clarke", "Jean-Luc Ponty", "Joe Pass", "Jim Hall", "Bill Frisell", "Pat Metheny"],
  "John McLaughlin": ["John Abercrombie", "Larry Coryell", "John Scofield", "Al Di Meola", "Pat Metheny", "Pat Martino", "Bill Frisell", "Chick Corea", "Tony Williams", "Mike Stern", "Jean-Luc Ponty", "Stanley Clarke"],
  "Al Di Meola": ["John McLaughlin", "Jean-Luc Ponty", "Pat Metheny", "Larry Coryell", "Stanley Clarke", "Chick Corea", "John Scofield", "Mike Stern", "Bill Frisell", "John Abercrombie", "Joe Pass", "Jaco Pastorius"],
  "Pat Metheny": ["John Abercrombie", "John Scofield", "Gary Burton", "Bill Frisell", "Ralph Towner", "John McLaughlin", "Chick Corea", "Mike Stern", "Michael Brecker", "Charlie Haden", "Al Di Meola", "Keith Jarrett"],
  "John Abercrombie": ["Ralph Towner", "Pat Metheny", "Gary Peacock", "Bobo Stenson", "Dave Holland", "John McLaughlin", "John Scofield", "Kenny Wheeler", "Bill Frisell", "Jack DeJohnette", "Peter Erskine", "Enrico Rava"],
  "Ralph Towner": ["John Abercrombie", "Jack DeJohnette", "Craig Taborn", "Gary Peacock", "Fred Hersch", "Bill Frisell", "Pat Metheny", "Keith Jarrett", "Paul Motian", "Enrico Rava", "Charlie Haden", "Charles Lloyd"],
  "John Scofield": ["Mike Stern", "Bill Frisell", "Pat Metheny", "John Abercrombie", "Charlie Hunter", "Joshua Redman", "Pat Martino", "John McLaughlin", "Stanley Clarke", "Gary Burton", "Joe Lovano", "Jack DeJohnette"],
  "Mike Stern": ["John Scofield", "Pat Metheny", "Michael Brecker", "Pat Martino", "John McLaughlin", "Joshua Redman", "Al Di Meola", "John Abercrombie", "Marcus Miller", "Stanley Clarke", "Kurt Rosenwinkel", "Chris Potter"],
  "Bill Frisell": ["Julian Lage", "Paul Motian", "John Scofield", "Ralph Towner", "John Abercrombie", "Pat Metheny", "Charlie Hunter", "Dave Douglas", "Charles Lloyd", "John McLaughlin", "Ambrose Akinmusire", "Dave Holland"],
  "Emily Remler": ["Pat Martino", "Wes Montgomery", "Joe Pass", "Tal Farlow", "Barney Kessel", "Kenny Burrell", "Grant Green", "Jim Hall", "Russell Malone", "Jimmy Raney", "Kurt Rosenwinkel", "Charlie Christian"],
  "Russell Malone": ["Barney Kessel", "Pat Martino", "Kenny Burrell", "Peter Bernstein", "Tal Farlow", "Joe Pass", "Wes Montgomery", "Herb Ellis", "Emily Remler", "Jimmy Raney", "Jim Hall", "Kurt Rosenwinkel"],
  "Mark Whitfield": ["Eddie Lang", "Jeff Tain Watts"],
  "Peter Bernstein": ["Chris Potter", "Kurt Rosenwinkel", "Russell Malone", "Pat Martino", "John Scofield", "Joe Pass", "Gilad Hekselman", "Jim Hall", "Roy Hargrove", "Barney Kessel", "Kenny Burrell", "Lage Lund"],
  "Kurt Rosenwinkel": ["Walter Smith III", "Gilad Hekselman", "Pat Martino", "Mark Turner", "Peter Bernstein", "Jim Hall", "Aaron Parks", "Bill Frisell", "Pat Metheny", "John Scofield", "Joe Pass", "Immanuel Wilkins"],
  "Charlie Hunter": ["John Scofield", "Kurt Elling", "Bill Frisell", "Julian Lage", "Joshua Redman", "Grant Green", "Lou Donaldson", "Mike Stern", "John Abercrombie", "Pat Metheny", "Christian McBride", "Kenny Burrell"],
  "Lage Lund": ["Seamus Blake", "Bill Stewart", "Eric Harland", "Dave Liebman", "Billy Hart"],
  "Gilad Hekselman": ["Kurt Rosenwinkel", "Walter Smith III", "Gerald Clayton", "Julian Lage", "Aaron Parks", "Immanuel Wilkins", "Bill Frisell", "Peter Bernstein", "Pat Metheny", "Brad Mehldau", "Joshua Redman", "John Scofield"],
  "Mary Halvorson": ["Makaya McCraven", "Ambrose Akinmusire", "Linda May Han Oh", "Dave Douglas", "Bill Frisell", "Andrew Hill", "Eric Dolphy", "Dave Holland", "John Zorn", "Charles Lloyd", "Vijay Iyer", "Ornette Coleman"],
  "Julian Lage": ["Bill Frisell", "John Scofield", "Charlie Hunter", "Aaron Parks", "Pat Metheny", "Charles Lloyd", "Brad Mehldau", "Ralph Towner", "Gilad Hekselman", "Joe Pass", "Joshua Redman", "Immanuel Wilkins"],
  "Lionel Hampton": ["Benny Goodman", "Count Basie", "Artie Shaw", "Coleman Hawkins", "Fats Waller", "Sidney Bechet", "Duke Ellington", "Illinois Jacquet", "Earl Hines", "Roy Eldridge", "Tommy Dorsey", "Art Tatum"],
  "Red Norvo": ["Lionel Hampton", "Bud Powell", "Dizzy Gillespie", "Fats Navarro", "Milt Jackson", "Benny Goodman", "Duke Ellington", "Clifford Brown", "Hank Jones", "Charlie Christian", "Coleman Hawkins", "Artie Shaw"],
  "Milt Jackson": ["Cannonball Adderley", "Freddie Hubbard", "Stanley Turrentine", "Dexter Gordon", "Art Pepper", "Sonny Rollins", "Kenny Burrell", "Bobby Hutcherson", "Coleman Hawkins", "Kenny Dorham", "Art Farmer", "Eddie Lockjaw Davis"],
  "Terry Gibbs": ["Joe Locke", "Al Cohn", "Frank Rosolino", "Ruby Braff", "Conte Candoli", "Stefon Harris", "Herb Geller", "Buck Clayton", "Walt Dickerson", "Bennie Green", "Arnett Cobb", "Al Haig"],
  "Cal Tjader": ["Herbie Mann", "Stan Getz", "Charles Earland", "Eddie Palmieri", "Jimmy Smith", "Bobby Hutcherson", "Gary Burton", "Gerry Mulligan", "Kenny Burrell", "Art Pepper", "Paul Desmond", "Ahmad Jamal"],
  "Bobby Hutcherson": ["Andrew Hill", "Lee Morgan", "Jackie McLean", "Joe Henderson", "Freddie Hubbard", "Hank Mobley", "Duke Pearson", "Wayne Shorter", "Stanley Turrentine", "Woody Shaw", "Grant Green", "Horace Silver"],
  "Gary Burton": ["Pat Metheny", "Chick Corea", "John Scofield", "Larry Coryell", "John Abercrombie", "Ralph Towner", "Kenny Wheeler", "Keith Jarrett", "Charles Lloyd", "Michael Brecker", "Joshua Redman", "Milt Jackson"],
  "Walt Dickerson": ["Andrew Cyrille", "Joe Locke", "Muhal Richard Abrams", "Cecil McBee", "Terry Gibbs", "Don Pullen", "Stefon Harris", "Bennie Green", "Frank Rosolino", "Bobby Hutcherson", "Tim Berne", "Billy Hart"],
  "Roy Ayers": ["Bobbi Humphrey", "Donald Byrd", "Ramsey Lewis", "Gary Bartz", "Les McCann", "Jimmy McGriff", "Herbie Hancock", "Gene Harris", "Herbie Mann", "Bobby Hutcherson", "Jack McDuff", "George Benson"],
  "Stefon Harris": ["Joe Locke", "Greg Osby", "Jeff Tain Watts", "Terry Gibbs", "Ravi Coltrane", "Bill Stewart", "Bob Berg", "Eric Harland", "Seamus Blake", "Randy Brecker", "Conrad Herwig", "Rudresh Mahanthappa"],
  "Joe Locke": ["Stefon Harris", "Terry Gibbs", "Steve Turre", "Walt Dickerson", "Jeff Tain Watts", "Jimmy Cobb", "Danilo Perez", "Bob Berg", "Conrad Herwig"],
  "Warren Wolf": ["Duke Pearson", "Joey Alexander", "Gary Burton", "Kenny Burrell", "Cal Tjader", "Bobby Hutcherson", "Russell Malone", "Gerald Clayton", "Joey DeFrancesco", "Milt Jackson", "Melissa Aldana", "Christian McBride"],
  "Wild Bill Davis": ["Barbara Dennerlein"],
  "Jimmy Smith": ["Stanley Turrentine", "Lou Donaldson", "Kenny Burrell", "Jimmy McGriff", "Lee Morgan", "Jack McDuff", "Hank Mobley", "Grant Green", "Freddie Hubbard", "Horace Silver", "Jackie McLean", "Donald Byrd"],
  "Jack McDuff": ["Jimmy McGriff", "Lou Donaldson", "Jimmy Smith", "Stanley Turrentine", "Shirley Scott", "Charles Earland", "Gene Harris", "Donald Byrd", "Bobbi Humphrey", "Lee Morgan", "Grant Green", "Les McCann"],
  "Jimmy McGriff": ["Jack McDuff", "Lou Donaldson", "Jimmy Smith", "Charles Earland", "Shirley Scott", "Donald Byrd", "Bobbi Humphrey", "Les McCann", "Ramsey Lewis", "Stanley Turrentine", "Grant Green", "Roy Ayers"],
  "Shirley Scott": ["Jack McDuff", "Jimmy McGriff", "Jimmy Smith", "Charles Earland", "Lou Donaldson", "Stanley Turrentine", "Duke Pearson", "Larry Young", "Mary Lou Williams", "Ramsey Lewis", "Freddie Hubbard", "Sonny Criss"],
  "Larry Young": ["Andrew Hill", "Jackie McLean", "Woody Shaw", "Eric Dolphy", "Elvin Jones", "Freddie Hubbard", "Wayne Shorter", "McCoy Tyner", "Jimmy Smith", "Dexter Gordon", "John Coltrane", "Archie Shepp"],
  "Don Patterson": ["Bennie Green", "Cecil Payne", "Pepper Adams", "Arnett Cobb", "Herb Geller", "Bobby Timmons", "Frank Wess", "Frank Rosolino", "Stanley Turrentine", "George Coleman"],
  "Charles Earland": ["Gary Bartz", "Jimmy McGriff", "Jack McDuff", "Jimmy Smith", "Ramsey Lewis", "Shirley Scott", "Cal Tjader", "Les McCann", "Lou Donaldson", "Freddie Hubbard", "Tal Farlow", "Donald Byrd"],
  "Dr. Lonnie Smith": ["Jimmy McGriff", "Donald Byrd", "Lou Donaldson", "Jimmy Smith", "Jack McDuff", "Grant Green", "Charles Earland", "Joey DeFrancesco", "Blue Mitchell", "Larry Young", "Shirley Scott", "Bobbi Humphrey"],
  "Joey DeFrancesco": ["Geri Allen", "Jimmy Smith", "Mike Stern", "Ron Carter", "John Scofield", "Joshua Redman", "Lee Morgan", "Bill Frisell", "Jason Moran", "Monty Alexander", "Ray Brown", "Oscar Peterson"],
  "Barbara Dennerlein": ["Wild Bill Davis", "Jimmy Smith", "Joey DeFrancesco"],
  "Cory Henry": ["Nate Smith", "Robert Glasper", "Avishai Cohen", "Julian Lage", "Jon Batiste", "Hiromi", "Herbie Hancock", "Joshua Redman", "Roy Hargrove", "Marcus Miller", "Brad Mehldau", "Nubya Garcia"],
  "Johnny Dodds": ["Pee Wee Russell", "Jimmie Noone", "Edmond Hall", "Barney Bigard", "Bobby Hackett"],
  "Jimmie Noone": ["Johnny Dodds", "Pee Wee Russell", "Edmond Hall", "Barney Bigard", "Bobby Hackett"],
  "Benny Goodman": ["Artie Shaw", "Count Basie", "Tommy Dorsey", "Lionel Hampton", "Duke Ellington", "Sidney Bechet", "Gene Krupa", "Fats Waller", "Bix Beiderbecke", "Louis Armstrong", "Charlie Christian", "Coleman Hawkins"],
  "Artie Shaw": ["Benny Goodman", "Tommy Dorsey", "Lionel Hampton", "Count Basie", "Chick Webb", "Gene Krupa", "Bix Beiderbecke", "Fats Waller", "Jack Teagarden", "Duke Ellington", "Earl Hines", "Lester Young"],
  "Barney Bigard": ["Edmond Hall", "Pee Wee Russell", "Johnny Dodds", "Jimmie Noone", "Bobby Hackett", "Buck Clayton", "Rex Stewart", "Cootie Williams", "Slam Stewart", "Stuff Smith"],
  "Edmond Hall": ["Barney Bigard", "Pee Wee Russell", "Johnny Dodds", "Jimmie Noone", "Bobby Hackett", "Rex Stewart", "Buck Clayton", "Cootie Williams", "Slam Stewart"],
  "Pee Wee Russell": ["Johnny Dodds", "Barney Bigard", "Edmond Hall", "Jimmie Noone", "Bobby Hackett", "Buck Clayton", "Rex Stewart", "Cootie Williams"],
  "Buddy DeFranco": ["Charlie Parker", "Lee Konitz", "Johnny Hodges", "Bob Brookmeyer", "Gene Ammons", "Ben Webster", "Dizzy Gillespie", "Duke Ellington", "Tommy Flanagan", "Lester Young", "John Coltrane", "Coleman Hawkins"],
  "Jimmy Giuffre": ["Shorty Rogers", "Paul Bley", "Lee Konitz", "Cecil Taylor", "Marion Brown", "Ornette Coleman", "Bud Shank", "Jackie McLean", "Eric Dolphy", "Albert Ayler", "Art Pepper", "Andrew Hill"],
  "Tony Scott": ["Jimmy Giuffre", "Buddy DeFranco"],
  "Eddie Daniels": ["Brad Mehldau", "Christian McBride", "Zoot Sims", "Chick Corea", "Dexter Gordon", "Anat Cohen", "Bud Shank", "Gerry Mulligan", "Ahmad Jamal", "Buddy DeFranco", "Michel Petrucciani", "Jimmy Giuffre"],
  "Don Byron": ["Bobby Hutcherson", "Brad Mehldau", "Bill Frisell", "Jason Moran", "Dave Douglas", "Charles Mingus", "Dave Holland", "Anat Cohen", "Joe Henderson", "Kurt Rosenwinkel", "Count Basie", "Charles Lloyd"],
  "Anat Cohen": ["Avishai Cohen", "Brad Mehldau", "Joe Lovano", "Michel Petrucciani", "Aaron Parks", "Bill Frisell", "Carmen McRae", "Jimmy Giuffre", "Keith Jarrett", "Don Byron", "Terri Lyne Carrington", "Kenny Burrell"],
  "Herbie Mann": ["Hubert Laws", "Cal Tjader", "Jimmy Smith", "Lee Morgan", "Herbie Hancock", "Les McCann", "Bobbi Humphrey", "Lou Donaldson", "Kenny Burrell", "Freddie Hubbard", "Roy Ayers", "Jeremy Steig"],
  "James Moody": ["Sonny Stitt", "Jackie McLean", "Sonny Criss", "Johnny Griffin", "Gene Ammons", "Dexter Gordon", "Stanley Turrentine", "Benny Carter", "Eddie Lockjaw Davis", "Lou Donaldson", "Benny Golson", "Art Pepper"],
  "Hubert Laws": ["Herbie Mann", "Freddie Hubbard", "Stanley Turrentine", "Bobbi Humphrey", "Les McCann", "Jeremy Steig", "Joe Sample", "George Benson", "Roy Ayers", "Ramsey Lewis", "Donald Byrd", "Cal Tjader"],
  "Jeremy Steig": ["Herbie Mann", "Hubert Laws", "Lou Donaldson", "Grant Green", "Jimmy McGriff", "Donald Byrd", "Bobbi Humphrey", "Stanley Turrentine", "Les McCann", "Kenny Burrell", "Jimmy Smith", "Milt Jackson"],
  "Bobbi Humphrey": ["Donald Byrd", "Roy Ayers", "Gene Harris", "Gary Bartz", "Jimmy McGriff", "Ramsey Lewis", "Les McCann", "Jack McDuff", "Hubert Laws", "Lou Donaldson", "Herbie Hancock", "Herbie Mann"],
  "Joe Venuti": ["Stuff Smith", "Ray Nance", "Johnny Dodds", "Pee Wee Russell", "Jimmie Noone", "Cootie Williams", "Edmond Hall"],
  "Stephane Grappelli": ["Django Reinhardt", "Michel Petrucciani", "Oscar Peterson", "Lionel Hampton", "Art Tatum", "Sidney Bechet", "Louis Armstrong", "Erroll Garner", "Jean-Luc Ponty", "Coleman Hawkins", "Fats Waller", "Dave Brubeck"],
  "Stuff Smith": ["Joe Venuti", "Rex Stewart", "Eddie Lang", "Cootie Williams", "Barney Bigard", "Pee Wee Russell", "Ray Nance", "Slam Stewart", "Edmond Hall", "Buck Clayton"],
  "Ray Nance": ["Joe Venuti", "Stuff Smith", "Buck Clayton", "Cootie Williams", "Harry Edison", "Rex Stewart", "Frank Wess", "Bobby Hackett", "Charlie Shavers", "Jon Faddis", "Roy Eldridge", "Harry Carney"],
  "Jean-Luc Ponty": ["Al Di Meola", "Stanley Clarke", "John McLaughlin", "Larry Coryell", "Tony Williams", "Jaco Pastorius", "Chick Corea", "Pat Metheny", "Herbie Hancock", "John Scofield", "Mike Stern", "Pat Martino"],
  "Billy Bang": ["Muhal Richard Abrams", "Hamiet Bluiett", "Andrew Cyrille", "Sunny Murray", "Dewey Redman", "Tim Berne", "Don Pullen", "Milford Graves", "Roswell Rudd", "Rudresh Mahanthappa", "Rashied Ali"],
  "Regina Carter": ["Cecile McLorin Salvant", "Mary Lou Williams", "Cannonball Adderley", "Dave Brubeck", "Stanley Turrentine", "David Sanborn", "Kenny Burrell", "Hubert Laws", "Charlie Parker", "Stuff Smith", "Betty Carter", "Jean-Luc Ponty"],
  "Mark Feldman": ["Milford Graves", "Tim Berne"],
  "Ella Fitzgerald": ["Sarah Vaughan", "Billie Holiday", "Louis Armstrong", "Nat King Cole", "Anita O'Day", "Carmen McRae", "Duke Ellington", "Oscar Peterson", "Count Basie", "Chet Baker", "Mel Torme", "Betty Carter"],
  "Billie Holiday": ["Ella Fitzgerald", "Sarah Vaughan", "Louis Armstrong", "Anita O'Day", "Chet Baker", "Nat King Cole", "Duke Ellington", "Carmen McRae", "Count Basie", "Lester Young", "Coleman Hawkins", "Betty Carter"],
  "Sarah Vaughan": ["Ella Fitzgerald", "Carmen McRae", "Billie Holiday", "Anita O'Day", "Betty Carter", "Count Basie", "Nat King Cole", "Mel Torme", "Louis Armstrong", "Cecile McLorin Salvant", "Cannonball Adderley", "Duke Ellington"],
  "Anita O'Day": ["Sarah Vaughan", "Carmen McRae", "Ella Fitzgerald", "Betty Carter", "Mel Torme", "Billie Holiday", "Nat King Cole", "Lionel Hampton", "Lester Young", "Coleman Hawkins", "Fats Waller", "Louis Armstrong"],
  "Carmen McRae": ["Sarah Vaughan", "Anita O'Day", "Betty Carter", "Ella Fitzgerald", "Cecile McLorin Salvant", "Mel Torme", "Billie Holiday", "Kurt Elling", "Art Farmer", "Ahmad Jamal", "Bud Powell", "Ben Webster"],
  "Betty Carter": ["Carmen McRae", "Sarah Vaughan", "Anita O'Day", "Kurt Elling", "Cecile McLorin Salvant", "Ella Fitzgerald", "Billie Holiday", "Mel Torme", "Archie Shepp", "Art Tatum", "Gregory Porter"],
  "Mel Torme": ["Nat King Cole", "Anita O'Day", "Sarah Vaughan", "Ella Fitzgerald", "Carmen McRae", "Artie Shaw", "Oscar Peterson", "Betty Carter", "Kurt Elling", "Louis Armstrong", "Billie Holiday", "Benny Goodman"],
  "Jon Hendricks": ["Carmen McRae", "Sarah Vaughan", "Kurt Elling", "Anita O'Day", "Cecile McLorin Salvant", "Ella Fitzgerald", "Gregory Porter", "Betty Carter", "Mel Torme", "Oscar Peterson", "Billie Holiday"],
  "Eddie Jefferson": ["J.J. Johnson", "Clifford Brown", "Freddie Hubbard", "Art Pepper", "Carmen McRae", "Horace Silver", "Dizzy Gillespie", "Art Blakey", "McCoy Tyner", "Sarah Vaughan", "Hank Jones", "Donald Byrd"],
  "Bobby McFerrin": ["Kurt Elling", "Sarah Vaughan", "Avishai Cohen", "Marcus Miller", "Donald Byrd", "Cecile McLorin Salvant", "Gregory Porter", "John Scofield", "Wynton Marsalis", "Chick Corea", "Al Di Meola", "Louis Armstrong"],
  "Kurt Elling": ["Charlie Hunter", "Cecile McLorin Salvant", "Gregory Porter", "Betty Carter", "Monty Alexander", "Christian McBride", "Robert Glasper", "Carmen McRae", "David Sanborn", "Branford Marsalis", "Sarah Vaughan", "Kenny Barron"],
  "Cecile McLorin Salvant": ["Kurt Elling", "Christian McBride", "Gregory Porter", "Sullivan Fortner", "Joshua Redman", "Linda May Han Oh", "Immanuel Wilkins", "Terri Lyne Carrington", "Betty Carter", "Charles Lloyd", "Lakecia Benjamin", "Sarah Vaughan"],
  "Gregory Porter": ["Kurt Elling", "Christian McBride", "Cecile McLorin Salvant", "George Benson", "Marcus Miller"],
};
